import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { createHash, randomUUID } from 'node:crypto';
import { requireShopId } from '../../common/tenant';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import type { JwtAccessPayload } from '../auth/auth.service';
import { computePricingQuote, projectPointsBalance, projectSignedBalance, signedLedgerAmount } from './growth.rules';
import type { CreateCustomerDto, CreatePackageDto, CreatePromotionDto, CreateStoredValueAccountDto, CreateTierDto, EnrollCustomerDto, LoyaltyEntryDto, QuoteDto, RecordTipDto, SnapshotDto, StoredValueEntryDto } from './growth.types';

@Injectable()
export class CommerceGrowthService {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}

  listPromotions(actor:JwtAccessPayload){return this.prisma.promotionRule.findMany({where:{shopId:requireShopId(actor)},orderBy:[{active:'desc'},{priority:'desc'},{name:'asc'}]});}
  async createPromotion(actor:JwtAccessPayload,dto:CreatePromotionDto){const shopId=requireShopId(actor);if(dto.kind==='PERCENT'&&(!Number.isInteger(dto.valueBps)||Number(dto.valueBps)<0||Number(dto.valueBps)>10000))throw new BadRequestException('PERCENT promotion requires valueBps from 0 to 10000.');if(dto.kind==='FIXED'&&(!Number.isInteger(dto.amountMinor)||Number(dto.amountMinor)<0))throw new BadRequestException('FIXED promotion requires non-negative amountMinor.');const row=await this.prisma.promotionRule.create({data:{shopId,code:dto.code?.trim().toUpperCase(),name:dto.name,kind:dto.kind,valueBps:dto.valueBps,amountMinor:dto.amountMinor,priority:dto.priority??0,stackable:dto.stackable??true,exclusiveGroup:dto.exclusiveGroup,minSubtotalMinor:Math.max(0,dto.minSubtotalMinor??0),requiresCode:dto.requiresCode??Boolean(dto.code),startsAt:dto.startsAt?new Date(dto.startsAt):undefined,endsAt:dto.endsAt?new Date(dto.endsAt):undefined,conditions:(dto.conditions??{}) as Prisma.InputJsonValue}});await this.record(actor,'promotion.create','Created deterministic promotion rule',{promotionId:row.id,name:row.name});return row;}
  async createPackage(actor:JwtAccessPayload,dto:CreatePackageDto){const shopId=requireShopId(actor),shop=await this.prisma.shop.findUnique({where:{id:shopId},select:{currency:true}});if(!Number.isInteger(dto.priceMinor)||dto.priceMinor<0)throw new BadRequestException('Package price must be a non-negative integer.');const row=await this.prisma.packageDefinition.create({data:{shopId,name:dto.name,priceMinor:dto.priceMinor,currency:(dto.currency??shop?.currency??'EUR').toUpperCase(),components:dto.components as Prisma.InputJsonValue}});await this.record(actor,'package.create','Created package/bundle definition',{packageId:row.id,name:row.name});return row;}

  async quote(actor:JwtAccessPayload,dto:QuoteDto){const shopId=requireShopId(actor),now=new Date();const [rules,packages]=await Promise.all([this.prisma.promotionRule.findMany({where:{shopId,active:true}}),dto.packageIds?.length?this.prisma.packageDefinition.findMany({where:{shopId,id:{in:dto.packageIds},active:true}}):Promise.resolve([])]);const requestedIds=new Set(dto.promotionIds??[]),requestedCodes=new Set((dto.promotionCodes??[]).map(c=>c.toUpperCase()));const eligible=rules.filter(r=>(!r.startsAt||r.startsAt<=now)&&(!r.endsAt||r.endsAt>now)&&(!r.requiresCode||requestedIds.has(r.id)||(r.code?requestedCodes.has(r.code):false)));const packageMinor=packages.reduce((s,p)=>s+p.priceMinor,0);const subtotalMinor=dto.subtotalMinor+packageMinor;const quote=computePricingQuote({subtotalMinor,taxMinor:dto.taxMinor,tipMinor:dto.tipMinor,tipBps:dto.tipBps,promotions:eligible});return {...quote,packageMinor,packages:packages.map(p=>({id:p.id,name:p.name,priceMinor:p.priceMinor})),currency:packages[0]?.currency??null};}

  async snapshot(actor:JwtAccessPayload,dto:SnapshotDto){const shopId=requireShopId(actor),quote=await this.quote(actor,dto),shop=await this.prisma.shop.findUnique({where:{id:shopId},select:{currency:true}});const rules={appliedPromotions:quote.appliedPromotions,packages:quote.packages,packageMinor:quote.packageMinor};const payload={sourceType:dto.sourceType,sourceId:dto.sourceId,...quote,rules};const pricingHash=createHash('sha256').update(JSON.stringify(payload)).digest('hex');const row=await this.prisma.pricingSnapshot.upsert({where:{shopId_sourceType_sourceId_pricingHash:{shopId,sourceType:dto.sourceType,sourceId:dto.sourceId,pricingHash}},create:{shopId,sourceType:dto.sourceType,sourceId:dto.sourceId,subtotalMinor:quote.subtotalMinor,discountMinor:quote.discountMinor,taxMinor:quote.taxMinor,tipMinor:quote.tipMinor,totalMinor:quote.totalMinor,currency:(dto.currency??quote.currency??shop?.currency??'EUR').toUpperCase(),rules:rules as Prisma.InputJsonValue,pricingHash,createdById:actor.sub},update:{}});await this.record(actor,'pricing.snapshot','Created immutable server pricing snapshot',{snapshotId:row.id,sourceType:row.sourceType,sourceId:row.sourceId,totalMinor:row.totalMinor});return row;}

  async recordTip(actor:JwtAccessPayload,dto:RecordTipDto){const shopId=requireShopId(actor),shop=await this.prisma.shop.findUnique({where:{id:shopId},select:{currency:true}}),signed=signedLedgerAmount(dto.type,dto.amountMinor,['REFUND']);if(dto.guestCheckId&&!await this.prisma.guestCheck.findFirst({where:{id:dto.guestCheckId,shopId}}))throw new NotFoundException('Guest check not found.');if(dto.paymentId&&!await this.prisma.payment.findFirst({where:{id:dto.paymentId,shopId,status:'SUCCESS'}}))throw new ConflictException('Successful payment not found.');const row=await this.prisma.tipLedgerEntry.upsert({where:{shopId_correlationId:{shopId,correlationId:dto.correlationId}},create:{shopId,guestCheckId:dto.guestCheckId,paymentId:dto.paymentId,type:dto.type,amountMinor:signed,currency:(dto.currency??shop?.currency??'EUR').toUpperCase(),correlationId:dto.correlationId,reason:dto.reason,actorUserId:actor.sub},update:{}});await this.record(actor,'tip.record','Recorded append-only gratuity movement',{tipEntryId:row.id,type:row.type,amountMinor:row.amountMinor});return row;}

  listCustomers(actor:JwtAccessPayload){return this.prisma.customerProfile.findMany({where:{shopId:requireShopId(actor)},orderBy:{createdAt:'desc'}});}
  async createCustomer(actor:JwtAccessPayload,dto:CreateCustomerDto){const shopId=requireShopId(actor),email=dto.email?.trim().toLowerCase(),phone=dto.phone?.trim();if(!email&&!phone)throw new BadRequestException('Customer requires email or phone.');const existing=await this.prisma.customerProfile.findFirst({where:{shopId,OR:[...(email?[{email}]:[]),...(phone?[{phone}]:[])]}});if(existing)return existing;const row=await this.prisma.customerProfile.create({data:{shopId,name:dto.name,email,phone,marketingConsentAt:dto.marketingConsent?new Date():undefined,consentSource:dto.marketingConsent?dto.consentSource:undefined,notes:dto.notes}});await this.audit.record(actor,{section:'reservation',action:'customer.create',summary:'Created customer profile',meta:{customerId:row.id,hasMarketingConsent:Boolean(row.marketingConsentAt)}});return row;}
  async createTier(actor:JwtAccessPayload,dto:CreateTierDto){const shopId=requireShopId(actor);const row=await this.prisma.membershipTier.create({data:{shopId,name:dto.name,code:dto.code.toUpperCase(),rank:dto.rank??0,earnRateBasisPoints:Math.max(0,dto.earnRateBasisPoints??0),benefits:(dto.benefits??{}) as Prisma.InputJsonValue}});await this.record(actor,'membership.tier.create','Created membership tier',{tierId:row.id,code:row.code});return row;}
  async enroll(actor:JwtAccessPayload,customerId:string,dto:EnrollCustomerDto){const shopId=requireShopId(actor);await this.requireCustomer(shopId,customerId);const tier=await this.prisma.membershipTier.findFirst({where:{id:dto.tierId,shopId,active:true}});if(!tier)throw new NotFoundException('Membership tier not found.');const row=await this.prisma.customerMembership.upsert({where:{shopId_customerId:{shopId,customerId}},create:{shopId,customerId,tierId:tier.id,expiresAt:dto.expiresAt?new Date(dto.expiresAt):undefined},update:{tierId:tier.id,status:'ACTIVE',expiresAt:dto.expiresAt?new Date(dto.expiresAt):null}});await this.record(actor,'membership.enroll','Enrolled customer in membership tier',{customerId,tierId:tier.id});return row;}

  async loyalty(actor:JwtAccessPayload,customerId:string,dto:LoyaltyEntryDto){const shopId=requireShopId(actor);await this.requireCustomer(shopId,customerId);const points=this.signedPoints(dto.type,dto.points);const row=await this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`loyalty:${shopId}:${customerId}`}))`;const existing=await tx.loyaltyLedgerEntry.findUnique({where:{shopId_correlationId:{shopId,correlationId:dto.correlationId}}});if(existing)return existing;const prior=await tx.loyaltyLedgerEntry.findMany({where:{shopId,customerId},select:{points:true}});if(projectPointsBalance(prior)+points<0)throw new ConflictException('Loyalty redemption cannot create a negative points balance.');return tx.loyaltyLedgerEntry.create({data:{shopId,customerId,type:dto.type,points,sourceType:dto.sourceType,sourceId:dto.sourceId,correlationId:dto.correlationId,note:dto.note,actorUserId:actor.sub}});});await this.record(actor,'loyalty.ledger','Recorded append-only loyalty movement',{customerId,entryId:row.id,type:row.type,points:row.points});return {entry:row,balance:await this.loyaltyBalance(shopId,customerId)};}

  async createStoredAccount(actor:JwtAccessPayload,dto:CreateStoredValueAccountDto){const shopId=requireShopId(actor);if(dto.customerId)await this.requireCustomer(shopId,dto.customerId);const code=dto.code??randomUUID().replace(/-/g,'').slice(0,20).toUpperCase(),codeHash=this.hashCode(code),shop=await this.prisma.shop.findUnique({where:{id:shopId},select:{currency:true}});const row=await this.prisma.storedValueAccount.create({data:{shopId,customerId:dto.customerId,codeHash,currency:(dto.currency??shop?.currency??'EUR').toUpperCase()}});await this.record(actor,'stored-value.account.create','Created stored-value account',{accountId:row.id,customerId:row.customerId});return {account:row,code};}
  async storedValue(actor:JwtAccessPayload,accountId:string,dto:StoredValueEntryDto){const shopId=requireShopId(actor),account=await this.prisma.storedValueAccount.findFirst({where:{id:accountId,shopId,status:'ACTIVE'}});if(!account)throw new NotFoundException('Active stored-value account not found.');const amount=signedLedgerAmount(dto.type,dto.amountMinor,['REDEEM']);if(dto.paymentId&&!await this.prisma.payment.findFirst({where:{id:dto.paymentId,shopId,status:'SUCCESS'}}))throw new ConflictException('Successful payment not found for stored-value load.');const row=await this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`stored-value:${shopId}:${accountId}`}))`;const existing=await tx.storedValueLedgerEntry.findUnique({where:{shopId_correlationId:{shopId,correlationId:dto.correlationId}}});if(existing)return existing;const prior=await tx.storedValueLedgerEntry.findMany({where:{shopId,accountId},select:{amountMinor:true}});if(projectSignedBalance(prior)+amount<0)throw new ConflictException('Stored-value redemption cannot create a negative balance.');return tx.storedValueLedgerEntry.create({data:{shopId,accountId,type:dto.type,amountMinor:amount,currency:account.currency,sourceType:dto.sourceType,sourceId:dto.sourceId,paymentId:dto.paymentId,correlationId:dto.correlationId,note:dto.note,actorUserId:actor.sub}});});await this.record(actor,'stored-value.ledger','Recorded append-only stored-value movement',{accountId,entryId:row.id,type:row.type,amountMinor:row.amountMinor});return {entry:row,balanceMinor:await this.storedBalance(shopId,accountId)};}

  async customerHistory(actor:JwtAccessPayload,customerId:string){const shopId=requireShopId(actor),customer=await this.requireCustomer(shopId,customerId);const identity=[...(customer.email?[{guestEmail:customer.email}]:[]),...(customer.phone?[{guestPhone:customer.phone}]:[])];const [membership,loyalty,accounts,reservations,checks]=await Promise.all([this.prisma.customerMembership.findFirst({where:{shopId,customerId}}),this.prisma.loyaltyLedgerEntry.findMany({where:{shopId,customerId},orderBy:{createdAt:'desc'}}),this.prisma.storedValueAccount.findMany({where:{shopId,customerId},orderBy:{createdAt:'desc'}}),identity.length?this.prisma.reservation.findMany({where:{shopId,OR:identity},orderBy:{startsAt:'desc'},take:100}):Promise.resolve([]),identity.length?this.prisma.guestCheck.findMany({where:{shopId,OR:identity},orderBy:{createdAt:'desc'},take:100}):Promise.resolve([])]);const stored=await Promise.all(accounts.map(async account=>({account,balanceMinor:await this.storedBalance(shopId,account.id)})));return {customer,membership,loyaltyBalance:projectPointsBalance(loyalty),loyalty,storedValue:stored,reservations,guestChecks:checks};}

  private signedPoints(type:string,points:number){if(!Number.isInteger(points)||points===0)throw new BadRequestException('Points must be a non-zero integer.');if(type==='ADJUST'||type==='REVERSAL')return points;return ['REDEEM','EXPIRE'].includes(type)?-Math.abs(points):Math.abs(points);}
  private async loyaltyBalance(shopId:string,customerId:string){const rows=await this.prisma.loyaltyLedgerEntry.findMany({where:{shopId,customerId},select:{points:true}});return projectPointsBalance(rows);}
  private async storedBalance(shopId:string,accountId:string){const rows=await this.prisma.storedValueLedgerEntry.findMany({where:{shopId,accountId},select:{amountMinor:true}});return projectSignedBalance(rows);}
  private hashCode(code:string){return createHash('sha256').update(code.trim().toUpperCase()).digest('hex');}
  private async requireCustomer(shopId:string,id:string){const row=await this.prisma.customerProfile.findFirst({where:{id,shopId}});if(!row)throw new NotFoundException('Customer not found.');return row;}
  private record(actor:JwtAccessPayload,action:string,summary:string,meta:Record<string,unknown>){return this.audit.record(actor,{section:'finance',action,summary,meta});}
}
