import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { requireShopId } from '../../common/tenant';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import type { JwtAccessPayload } from '../auth/auth.service';
import { intervalsOverlap } from './growth.rules';
import type { CreateEventHoldDto, CreateEventProposalDto, CreateEventScheduleDto, MarkEventSchedulePaidDto, StartEventDto } from './growth.types';

@Injectable()
export class EventsGrowthService {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}

  async detail(actor:JwtAccessPayload,eventRequestId:string){const shopId=requireShopId(actor);await this.requireEvent(shopId,eventRequestId);const [proposals,holds,payments,execution]=await Promise.all([this.prisma.eventProposal.findMany({where:{shopId,eventRequestId},orderBy:{version:'desc'}}),this.prisma.eventResourceHold.findMany({where:{shopId,eventRequestId},orderBy:{startsAt:'asc'}}),this.prisma.eventPaymentSchedule.findMany({where:{shopId,eventRequestId},orderBy:{dueAt:'asc'}}),this.prisma.eventExecution.findFirst({where:{shopId,eventRequestId}})]);return {eventRequestId,proposals,holds,paymentSchedule:payments,execution};}

  async createProposal(actor:JwtAccessPayload,eventRequestId:string,dto:CreateEventProposalDto){const shopId=requireShopId(actor);await this.requireEvent(shopId,eventRequestId);if(!Number.isInteger(dto.subtotalMinor)||dto.subtotalMinor<0||!Number.isInteger(dto.depositMinor??0)||Number(dto.depositMinor??0)<0)throw new BadRequestException('Proposal money fields must be non-negative integers.');const shop=await this.prisma.shop.findUnique({where:{id:shopId},select:{currency:true}});const row=await this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`event-proposal:${shopId}:${eventRequestId}`}))`;const latest=await tx.eventProposal.findFirst({where:{shopId,eventRequestId},orderBy:{version:'desc'}});return tx.eventProposal.create({data:{shopId,eventRequestId,version:(latest?.version??0)+1,subtotalMinor:dto.subtotalMinor,depositMinor:dto.depositMinor??0,currency:(dto.currency??shop?.currency??'EUR').toUpperCase(),terms:dto.terms as Prisma.InputJsonValue,validUntil:dto.validUntil?new Date(dto.validUntil):undefined,createdById:actor.sub}});});await this.record(actor,'event.proposal.create','Created versioned event proposal',{eventRequestId,proposalId:row.id,version:row.version});return row;}
  async setProposalStatus(actor:JwtAccessPayload,id:string,status:'SENT'|'REJECTED'){const shopId=requireShopId(actor),row=await this.prisma.eventProposal.findFirst({where:{id,shopId}});if(!row)throw new NotFoundException('Event proposal not found.');if(!['DRAFT','SENT'].includes(row.status))throw new ConflictException('Accepted/superseded proposals cannot be changed this way.');const updated=await this.prisma.eventProposal.update({where:{id},data:{status}});await this.record(actor,'event.proposal.status','Changed event proposal status',{proposalId:id,status});return updated;}

  async createHold(actor:JwtAccessPayload,eventRequestId:string,dto:CreateEventHoldDto){const shopId=requireShopId(actor);await this.requireEvent(shopId,eventRequestId);const start=new Date(dto.startsAt),end=new Date(dto.endsAt);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)throw new BadRequestException('Hold end must be after start.');if(!await this.prisma.resource.findFirst({where:{id:dto.resourceId,shopId}}))throw new NotFoundException('Resource not found.');const row=await this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`event-resource:${shopId}:${dto.resourceId}`}))`;const reservations=await tx.reservation.findMany({where:{shopId,resourceId:dto.resourceId,startsAt:{lt:end},endsAt:{gt:start}}});if(reservations.some(r=>!['CANCELED','NO_SHOW'].includes(r.status)))throw new ConflictException('Resource is already reserved in this interval.');const holds=await tx.eventResourceHold.findMany({where:{shopId,resourceId:dto.resourceId,status:{in:['HOLD','CONFIRMED']}}});if(holds.some(h=>intervalsOverlap(start,end,h.startsAt,h.endsAt)))throw new ConflictException('Resource already has an event hold in this interval.');return tx.eventResourceHold.create({data:{shopId,eventRequestId,resourceId:dto.resourceId,startsAt:start,endsAt:end,expiresAt:dto.expiresAt?new Date(dto.expiresAt):undefined,createdById:actor.sub}});});await this.record(actor,'event.hold.create','Placed event resource hold',{eventRequestId,holdId:row.id,resourceId:row.resourceId});return row;}

  async acceptProposal(actor:JwtAccessPayload,id:string){const shopId=requireShopId(actor);const result=await this.prisma.$transaction(async tx=>{const proposal=await tx.eventProposal.findFirst({where:{id,shopId}});if(!proposal)throw new NotFoundException('Event proposal not found.');await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`event-accept:${shopId}:${proposal.eventRequestId}`}))`;if(proposal.status==='ACCEPTED')return proposal;if(proposal.validUntil&&proposal.validUntil<new Date())throw new ConflictException('Event proposal has expired.');const event=await tx.eventRequest.findFirst({where:{id:proposal.eventRequestId,shopId}});if(!event)throw new NotFoundException('Event request not found.');const holds=await tx.eventResourceHold.findMany({where:{shopId,eventRequestId:event.id,status:'HOLD'},orderBy:{startsAt:'asc'}});for(const hold of holds){const reservation=await tx.reservation.create({data:{shopId,resourceId:hold.resourceId,guestName:event.guestName,guestEmail:event.guestEmail,guestPhone:event.guestPhone,partySize:event.partySize,startsAt:hold.startsAt,endsAt:hold.endsAt,notes:`Event ${event.id} / proposal v${proposal.version}`}});await tx.eventResourceHold.update({where:{id:hold.id},data:{status:'CONFIRMED',reservationId:reservation.id}});}await tx.eventProposal.updateMany({where:{shopId,eventRequestId:event.id,id:{not:id},status:{in:['DRAFT','SENT']}},data:{status:'SUPERSEDED'}});return tx.eventProposal.update({where:{id},data:{status:'ACCEPTED'}});});await this.record(actor,'event.proposal.accept','Accepted proposal and converted resource holds to reservations',{proposalId:id,eventRequestId:result.eventRequestId});return result;}

  async createPaymentSchedule(actor:JwtAccessPayload,eventRequestId:string,dto:CreateEventScheduleDto){const shopId=requireShopId(actor);await this.requireEvent(shopId,eventRequestId);if(!Number.isInteger(dto.amountMinor)||dto.amountMinor<=0)throw new BadRequestException('Scheduled payment amount must be positive.');if(dto.proposalId&&!await this.prisma.eventProposal.findFirst({where:{id:dto.proposalId,shopId,eventRequestId}}))throw new NotFoundException('Proposal not found for this event.');const shop=await this.prisma.shop.findUnique({where:{id:shopId},select:{currency:true}});const row=await this.prisma.eventPaymentSchedule.create({data:{shopId,eventRequestId,proposalId:dto.proposalId,label:dto.label,dueAt:new Date(dto.dueAt),amountMinor:dto.amountMinor,currency:(dto.currency??shop?.currency??'EUR').toUpperCase()}});await this.record(actor,'event.payment.schedule','Scheduled event payment',{eventRequestId,scheduleId:row.id,amountMinor:row.amountMinor});return row;}
  async markPaymentPaid(actor:JwtAccessPayload,id:string,dto:MarkEventSchedulePaidDto){const shopId=requireShopId(actor),schedule=await this.prisma.eventPaymentSchedule.findFirst({where:{id,shopId}});if(!schedule)throw new NotFoundException('Event payment schedule item not found.');const payment=await this.prisma.payment.findFirst({where:{id:dto.paymentId,shopId,status:'SUCCESS'}});if(!payment)throw new ConflictException('Successful checkout payment not found.');const amountMinor=Math.round(Number(payment.amount.toString())*100);if(amountMinor<schedule.amountMinor)throw new ConflictException('Payment is smaller than the scheduled event amount.');const row=await this.prisma.eventPaymentSchedule.update({where:{id},data:{status:'PAID',paymentId:payment.id,paidAt:new Date()}});await this.record(actor,'event.payment.paid','Linked successful payment to event schedule',{scheduleId:id,paymentId:payment.id});return row;}

  async startExecution(actor:JwtAccessPayload,eventRequestId:string,dto:StartEventDto){const shopId=requireShopId(actor);await this.requireEvent(shopId,eventRequestId);if(dto.guestCheckId&&!await this.prisma.guestCheck.findFirst({where:{id:dto.guestCheckId,shopId}}))throw new NotFoundException('Guest check not found.');const row=await this.prisma.eventExecution.upsert({where:{eventRequestId},create:{shopId,eventRequestId,guestCheckId:dto.guestCheckId,status:'IN_PROGRESS',startedAt:new Date()},update:{guestCheckId:dto.guestCheckId,status:'IN_PROGRESS',startedAt:new Date(),canceledAt:null,completedAt:null}});await this.record(actor,'event.execution.start','Started event execution',{eventRequestId,executionId:row.id,guestCheckId:row.guestCheckId});return row;}
  async finishExecution(actor:JwtAccessPayload,eventRequestId:string,outcome:'COMPLETED'|'CANCELED'){const shopId=requireShopId(actor),row=await this.prisma.eventExecution.findFirst({where:{shopId,eventRequestId}});if(!row)throw new NotFoundException('Event execution not found.');const updated=await this.prisma.eventExecution.update({where:{id:row.id},data:outcome==='COMPLETED'?{status:outcome,completedAt:new Date()}:{status:outcome,canceledAt:new Date()}});if(outcome==='CANCELED')await this.prisma.eventResourceHold.updateMany({where:{shopId,eventRequestId,status:'HOLD'},data:{status:'RELEASED'}});await this.record(actor,'event.execution.finish','Finished event execution',{eventRequestId,outcome});return updated;}

  private async requireEvent(shopId:string,id:string){const row=await this.prisma.eventRequest.findFirst({where:{id,shopId}});if(!row)throw new NotFoundException('Event request not found.');return row;}
  private record(actor:JwtAccessPayload,action:string,summary:string,meta:Record<string,unknown>){return this.audit.record(actor,{section:'reservation',action,summary,meta});}
}
