import { ConflictException } from '@nestjs/common';
import { GrowthCrmService } from './growth-crm.service';

const actor = { sub: 'user-1', shopId: 'shop-1' } as any;

function makeService(prismaOverrides: Record<string, any> = {}) {
  const prisma: any = {
    customerProfile: { findFirst: jest.fn() },
    ...prismaOverrides,
  };
  const audit = { record: jest.fn().mockResolvedValue(undefined) } as any;
  return { service: new GrowthCrmService(prisma, audit), prisma, audit };
}

describe('GrowthCrmService integrity gates', () => {
  afterEach(() => jest.restoreAllMocks());

  it('merges duplicate identities and dependent CRM rows under deterministic locks', async () => {
    const canonical = {
      id: 'customer-a',
      name: 'Canonical',
      email: 'a@example.com',
      phone: null,
      marketingConsentAt: null,
      consentSource: null,
      notes: null,
    };
    const merged = {
      id: 'customer-b',
      name: 'Duplicate',
      email: null,
      phone: '+48123456789',
      marketingConsentAt: new Date('2026-08-01T00:00:00Z'),
      consentSource: 'WEB',
      notes: 'keep if canonical empty',
    };
    const tx: any = {
      $executeRaw: jest.fn().mockResolvedValue(0),
      customerProfile: {
        findFirst: jest
          .fn()
          .mockResolvedValueOnce(canonical)
          .mockResolvedValueOnce(merged),
        update: jest.fn().mockImplementation(async ({ data }: any) => ({
          ...canonical,
          ...data,
        })),
        delete: jest.fn().mockResolvedValue(merged),
      },
      customerIdentity: {
        findMany: jest.fn().mockResolvedValue([
          {
            id: 'identity-b-phone',
            kind: 'PHONE',
            normalizedValue: '+48123456789',
          },
        ]),
        findFirst: jest.fn().mockResolvedValue(null),
        update: jest.fn().mockResolvedValue({ id: 'identity-b-phone' }),
        delete: jest.fn(),
      },
      loyaltyLedgerEntry: {
        updateMany: jest.fn().mockResolvedValue({ count: 2 }),
      },
      storedValueAccount: {
        updateMany: jest.fn().mockResolvedValue({ count: 1 }),
      },
      customerVisit: {
        updateMany: jest.fn().mockResolvedValue({ count: 3 }),
      },
      reviewVisitProof: {
        updateMany: jest.fn().mockResolvedValue({ count: 1 }),
      },
      customerMembership: {
        findFirst: jest
          .fn()
          .mockResolvedValueOnce({
            id: 'membership-a',
            tierId: 'tier-basic',
            expiresAt: null,
          })
          .mockResolvedValueOnce({
            id: 'membership-b',
            tierId: 'tier-vip',
            expiresAt: new Date('2027-01-01T00:00:00Z'),
          }),
        update: jest.fn().mockResolvedValue({ id: 'membership-a' }),
        delete: jest.fn().mockResolvedValue({ id: 'membership-b' }),
      },
      membershipTier: {
        findMany: jest.fn().mockResolvedValue([
          { id: 'tier-basic', rank: 1 },
          { id: 'tier-vip', rank: 10 },
        ]),
      },
      customerMergeAudit: {
        create: jest.fn().mockImplementation(async ({ data }: any) => ({
          id: 'merge-audit-1',
          ...data,
        })),
      },
    };
    const { service } = makeService({
      $transaction: jest.fn(async (callback: any) => callback(tx)),
    });

    const result = await service.mergeCustomer(actor, 'customer-a', {
      mergedCustomerId: 'customer-b',
      reason: 'Verified duplicate',
    });

    expect(tx.$executeRaw).toHaveBeenCalledTimes(2);
    expect(tx.customerIdentity.update).toHaveBeenCalledWith({
      where: { id: 'identity-b-phone' },
      data: { customerId: 'customer-a' },
    });
    expect(tx.loyaltyLedgerEntry.updateMany).toHaveBeenCalledWith({
      where: { shopId: 'shop-1', customerId: 'customer-b' },
      data: { customerId: 'customer-a' },
    });
    expect(tx.storedValueAccount.updateMany).toHaveBeenCalled();
    expect(tx.customerVisit.updateMany).toHaveBeenCalled();
    expect(tx.reviewVisitProof.updateMany).toHaveBeenCalled();
    expect(tx.customerMembership.update).toHaveBeenCalledWith({
      where: { id: 'membership-a' },
      data: {
        tierId: 'tier-vip',
        expiresAt: new Date('2027-01-01T00:00:00Z'),
      },
    });
    expect(tx.customerProfile.delete).toHaveBeenCalledWith({
      where: { id: 'customer-b' },
    });
    expect(result.referenceCounts).toEqual({
      identities: 1,
      loyaltyEntries: 2,
      storedValueAccounts: 1,
      visits: 3,
      reviewProofs: 1,
      membership: 'upgraded',
    });
  });

  it('reverses only the positive net reward generated by the refunded source', async () => {
    const tx: any = {
      $executeRaw: jest.fn().mockResolvedValue(0),
      loyaltyLedgerEntry: {
        findUnique: jest.fn().mockResolvedValue(null),
        findMany: jest.fn().mockResolvedValue([
          { points: 100 },
          { points: -20 },
        ]),
        create: jest.fn().mockImplementation(async ({ data }: any) => ({
          id: 'loyalty-reversal-1',
          ...data,
        })),
      },
    };
    const { service } = makeService({
      customerProfile: {
        findFirst: jest.fn().mockResolvedValue({ id: 'customer-1' }),
      },
      loyaltyLedgerEntry: {
        findMany: jest.fn().mockResolvedValue([{ points: 20 }]),
      },
      $transaction: jest.fn(async (callback: any) => callback(tx)),
    });

    const result = await service.reverseRewards(actor, 'customer-1', {
      sourceType: 'PAYMENT',
      sourceId: 'payment-1',
      correlationId: 'refund-1:rewards',
    });

    expect(tx.$executeRaw).toHaveBeenCalledTimes(1);
    expect(tx.loyaltyLedgerEntry.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        type: 'REVERSAL',
        points: -80,
        sourceType: 'PAYMENT',
        sourceId: 'payment-1',
      }),
    });
    expect(result.reversedPoints).toBe(80);
  });

  it('prevents concurrent stored-value redemption from crossing below zero', async () => {
    const tx: any = {
      $executeRaw: jest.fn().mockResolvedValue(0),
      storedValueLedgerEntry: {
        findUnique: jest.fn().mockResolvedValue(null),
        findMany: jest.fn().mockResolvedValue([{ amountMinor: 500 }]),
        create: jest.fn(),
      },
    };
    const { service } = makeService({
      storedValueAccount: {
        findFirst: jest().fn,
      },
    });
    // Replace the accidental generic placeholder with the real active account mock.
    (service as any).prisma.storedValueAccount = {
      findFirst: jest.fn().mockResolvedValue({
        id: 'wallet-1',
        currency: 'EUR',
        status: 'ACTIVE',
      }),
    };
    (service as any).prisma.$transaction = jest.fn(async (callback: any) => callback(tx));

    await expect(
      service.storedValue(actor, 'wallet-1', {
        type: 'REDEEM',
        amountMinor: 600,
        correlationId: 'wallet-redeem-1',
      }),
    ).rejects.toBeInstanceOf(ConflictException);

    expect(tx.$executeRaw).toHaveBeenCalledTimes(1);
    expect(tx.storedValueLedgerEntry.create).not.toHaveBeenCalled();
  });

  it('records verified visits from canonical settlement evidence only', async () => {
    const upsert = jest.fn().mockImplementation(async ({ create }: any) => ({
      id: 'visit-1',
      ...create,
    }));
    const { service } = makeService({
      customerProfile: {
        findFirst: jest.fn().mockResolvedValue({ id: 'customer-1' }),
      },
      customerVisit: { upsert },
    });
    jest.spyOn(service as any, 'visitEvidence').mockResolvedValue({
      completedAt: new Date('2026-08-11T10:00:00Z'),
      reservationId: 'reservation-1',
      guestCheckId: 'check-1',
      operationsSessionId: null,
      eventRequestId: null,
      settledAmountMinor: 4500,
      currency: 'EUR',
    });

    const visit = await service.recordVisit(actor, 'customer-1', {
      sourceType: 'RESERVATION',
      sourceId: 'reservation-1',
    });

    expect(upsert).toHaveBeenCalledWith(
      expect.objectContaining({
        create: expect.objectContaining({
          customerId: 'customer-1',
          reservationId: 'reservation-1',
          settledAmountMinor: 4500,
          currency: 'EUR',
          proofHash: expect.any(String),
        }),
      }),
    );
    expect(visit.id).toBe('visit-1');
  });

  it('issues a one-time review proof token without storing the raw token', async () => {
    const create = jest.fn().mockImplementation(async ({ data }: any) => ({
      id: 'proof-1',
      ...data,
    }));
    const { service } = makeService({
      customerVisit: {
        findFirst: jest.fn().mockResolvedValue({ id: 'visit-1', customerId: 'customer-1' }),
      },
      reviewVisitProof: { create },
    });

    const result = await service.issueReviewProof(actor, 'customer-1', 'visit-1');
    const storedHash = create.mock.calls[0][0].data.publicTokenHash;

    expect(result.token).toEqual(expect.any(String));
    expect(result.token).not.toBe(storedHash);
    expect(storedHash).toMatch(/^[a-f0-9]{64}$/);
  });
});
