-- CreateEnum
CREATE TYPE "MealPeriod" AS ENUM ('ALL_DAY', 'BREAKFAST', 'BRUNCH', 'LUNCH', 'AFTERNOON', 'DINNER', 'LATE_NIGHT');

-- AlterTable MenuSection
ALTER TABLE "MenuSection" ADD COLUMN IF NOT EXISTS "mealPeriod" "MealPeriod",
ADD COLUMN IF NOT EXISTS "availableFrom" TEXT,
ADD COLUMN IF NOT EXISTS "availableTo" TEXT,
ADD COLUMN IF NOT EXISTS "availableDays" TEXT NOT NULL DEFAULT '0,1,2,3,4,5,6';

-- AlterTable MenuItem
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "imageUrl2" TEXT,
ADD COLUMN IF NOT EXISTS "trackStock" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "useSectionTiming" BOOLEAN NOT NULL DEFAULT true;
