import { Prisma,PrismaClient } from '@prisma/client';
const prisma=new PrismaClient();
function assert(v:unknown,m:string):asserts v{if(!v)throw new Error(`PHASE7_ASSERT: ${m}`);}
async function main(){
 const required:{[k:string]:string[]}={InventoryProfile:['negativeStockPolicy','costingMethod','restockOnRefund','wasteApprovalThresholdMinor'],StockItem:['purchaseUnit','purchaseToInventoryFactorMilli','defaultLocationId','reorderLevelMilli','preferredSupplierId','purchaseTaxCode','purchaseTaxRateBps','latestPurchaseCostMinor','negativeStockAllowed'],Supplier:['legalName','displayName','taxIdentifier','paymentTerms','leadTimeDays','contactName'],Recipe:['version'],StockMovement:['reasonCode','approvalRef','attachmentUrl'],PurchaseOrder:['approvedAt','approvedById','sentAt','sentById','cancelledAt','cancelledById','documentRef'],PurchaseOrderLine:['orderedPurchaseMilli','receivedMilli'],GoodsReceipt:['idempotencyKey','invoiceRef','documentRef'],GoodsReceiptLine:['purchaseQuantityMilli','damagedMilli','lotBatch','expiresAt'],Stocktake:['blindCount','snapshotAt','submittedAt','approvedAt','approvedById','version'],StocktakeLine:['countedAt'],StockTransfer:['status','unitCostMinor','receivedMilli','damagedMilli','missingMilli','receivedById','receivedAt','note']};
 for(const [table,cols] of Object.entries(required)){const rows=await prisma.$queryRaw<Array<{column_name:string}>>(Prisma.sql`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=${table} AND column_name IN (${Prisma.join(cols)})`);assert(rows.length===cols.length,`${table} columns ${rows.length}/${cols.length}`);}
 const cs=await prisma.$queryRaw<Array<{conname:string}>>`SELECT conname FROM pg_constraint WHERE conname IN ('InventoryProfile_negativeStockPolicy_check','InventoryProfile_costingMethod_check','InventoryProfile_wasteApprovalThreshold_check','StockItem_purchaseFactor_check','PurchaseOrder_status_check','Stocktake_status_check','StockTransfer_status_check')`;assert(cs.length===7,'Phase 7 constraints are incomplete');
 const mk=await prisma.$queryRaw<Array<{indexname:string}>>`SELECT indexname FROM pg_indexes WHERE schemaname='public' AND tablename='StockMovement' AND indexdef ILIKE '%UNIQUE%' AND indexdef ILIKE '%movementKey%'`;assert(mk.length>0,'StockMovement.movementKey must remain unique');
 const prefix=`p7_${Date.now()}`,userId=`${prefix}_u`,shopId=`${prefix}_s`,locA=`${prefix}_a`,locB=`${prefix}_b`,itemId=`${prefix}_i`;
 await prisma.user.create({data:{id:userId,email:`${prefix}@gospots.invalid`,name:'P7 Assert',passwordHash:'x'}});await prisma.shop.create({data:{id:shopId,name:'P7 Assert',slug:prefix,dashboardKey:`${prefix}_key`,ownerId:userId,currency:'PLN',timezone:'Europe/Warsaw'}});await prisma.inventoryProfile.create({data:{shopId,enabled:true,legacyDualMode:false,negativeStockPolicy:'BLOCK'}});await prisma.inventoryLocation.createMany({data:[{id:locA,shopId,name:'Main'},{id:locB,shopId,name:'Bar'}]});await prisma.stockItem.create({data:{id:itemId,shopId,name:'Ingredient',sku:`${prefix}_sku`,unit:'ml',purchaseUnit:'bottle',purchaseToInventoryFactorMilli:750000,defaultLocationId:locA,weightedAverageCostMinor:200}});
 await prisma.stockMovement.createMany({data:[{shopId,stockItemId:itemId,locationId:locA,kind:'RECEIPT',quantityMilli:10000,unitCostMinor:200,totalCostMinor:2000,referenceType:'P7_PILOT',referenceId:prefix,movementKey:`${prefix}:r`,actorUserId:userId},{shopId,stockItemId:itemId,locationId:locA,kind:'TRANSFER_OUT',quantityMilli:-2000,unitCostMinor:200,totalCostMinor:400,referenceType:'P7_PILOT',referenceId:prefix,movementKey:`${prefix}:o`,actorUserId:userId},{shopId,stockItemId:itemId,locationId:locB,kind:'TRANSFER_IN',quantityMilli:1900,unitCostMinor:200,totalCostMinor:380,referenceType:'P7_PILOT',referenceId:prefix,movementKey:`${prefix}:i`,actorUserId:userId},{shopId,stockItemId:itemId,locationId:locB,kind:'WASTE',quantityMilli:-100,unitCostMinor:200,totalCostMinor:20,referenceType:'P7_PILOT',referenceId:prefix,movementKey:`${prefix}:w`,reasonCode:'SPOILAGE',actorUserId:userId}]});
 const movements=await prisma.stockMovement.findMany({where:{shopId},select:{quantityMilli:true,movementKey:true,kind:true}});assert(movements.reduce((s,m)=>s+m.quantityMilli,0)===9800,'movement ledger did not reconcile');assert(movements.every(m=>m.movementKey&&m.kind),'pilot contains unexplained movement');
 await prisma.stockMovement.deleteMany({where:{shopId}});await prisma.stockItem.deleteMany({where:{shopId}});await prisma.inventoryLocation.deleteMany({where:{shopId}});await prisma.inventoryProfile.deleteMany({where:{shopId}});await prisma.shop.deleteMany({where:{id:shopId}});await prisma.user.deleteMany({where:{id:userId}});
 console.log('PHASE7_INVENTORY_ASSERT=PASS');
}
main().finally(()=>prisma.$disconnect()).catch(e=>{console.error(e);process.exitCode=1;});
