import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { requireShopId } from '../../common/tenant';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import type { JwtAccessPayload } from '../auth/auth.types';
import { computeRevenueSince } from '../finance/finance-analytics.util';
import { ClockInDto, CreateEmployeeRateDto, CreateJobRoleDto, CreateScheduleEntryDto, CreateTimeAdjustmentDto, DecideTimeAdjustmentDto, StartBreakDto } from './dto/workforce.dto';

type EffectivePunch = { id:string; membershipId:string; startedAt:Date; endedAt:Date|null; unpaidBreakSeconds:number; workedSeconds:number; hourlyRateMinor:number; currency:string; laborCostMinor:number };
export function intervalsOverlap(aStart:Date,aEnd:Date,bStart:Date,bEnd:Date){return aStart < bEnd && bStart < aEnd;}
export function calculateWorkedSeconds(input:{startedAt:Date;endedAt:Date;unpaidBreakSeconds:number}){return Math.max(0,Math.floor((input.endedAt.getTime()-input.startedAt.getTime())/1000)-Math.max(0,input.unpaidBreakSeconds));}
export function calculateLaborCostMinor(workedSeconds:number,hourlyRateMinor:number){return Math.max(0,Math.round((workedSeconds*hourlyRateMinor)/3600));}

@Injectable()
export class WorkforceService {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
  async roster(actor:JwtAccessPayload){const shopId=requireShopId(actor);const memberships=await this.prisma.membership.findMany({where:{shopId},include:{user:true},orderBy:{createdAt:'asc'}});const roles=await this.prisma.jobRole.findMany({where:{shopId,active:true},orderBy:[{sortOrder:'asc'},{name:'asc'}]});return {memberships:memberships.map(m=>({id:m.id,userId:m.userId,name:m.user.name??m.user.email,email:m.user.email,role:m.role})),roles};}
  createJobRole(actor:JwtAccessPayload,dto:CreateJobRoleDto){return this.prisma.jobRole.create({data:{shopId:requireShopId(actor),name:dto.name,code:dto.code,sortOrder:dto.sortOrder??0}});}
  async createRate(actor:JwtAccessPayload,dto:CreateEmployeeRateDto){const shopId=requireShopId(actor);await this.requireMembership(shopId,dto.membershipId);await this.requireRole(shopId,dto.jobRoleId);const from=new Date(dto.effectiveFrom),to=dto.effectiveTo?new Date(dto.effectiveTo):null;if(to&&to<=from)throw new BadRequestException('Rate effectiveTo must be after effectiveFrom.');const shop=await this.prisma.shop.findUnique({where:{id:shopId},select:{currency:true}});const result=await this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`rate:${shopId}:${dto.membershipId}:${dto.jobRoleId}`}))`;const predecessor=await tx.employeeRate.findFirst({where:{shopId,membershipId:dto.membershipId,jobRoleId:dto.jobRoleId,effectiveFrom:{lt:from},effectiveTo:null},orderBy:{effectiveFrom:'desc'}});if(predecessor)await tx.employeeRate.update({where:{id:predecessor.id},data:{effectiveTo:from}});const overlap=await tx.employeeRate.findFirst({where:{shopId,membershipId:dto.membershipId,jobRoleId:dto.jobRoleId,...(predecessor?{id:{not:predecessor.id}}:{}),effectiveFrom:{lt:to??new Date('9999-12-31T23:59:59.999Z')},OR:[{effectiveTo:null},{effectiveTo:{gt:from}}]}});if(overlap)throw new ConflictException('Employee rate periods cannot overlap.');const row=await tx.employeeRate.create({data:{shopId,membershipId:dto.membershipId,jobRoleId:dto.jobRoleId,hourlyRateMinor:dto.hourlyRateMinor,currency:(dto.currency??shop?.currency??'EUR').toUpperCase(),effectiveFrom:from,effectiveTo:to,createdById:actor.sub}});return {row,closedRateId:predecessor?.id??null};});await this.record(actor,'workforce.rate.create','Created effective-dated employee rate',{employeeRateId:result.row.id,membershipId:result.row.membershipId,jobRoleId:result.row.jobRoleId,effectiveFrom:result.row.effectiveFrom,effectiveTo:result.row.effectiveTo,closedPreviousRateId:result.closedRateId});return result.row;}
  async createSchedule(actor:JwtAccessPayload,dto:CreateScheduleEntryDto){const shopId=requireShopId(actor);await this.requireMembership(shopId,dto.membershipId);await this.requireRole(shopId,dto.jobRoleId);const startsAt=new Date(dto.startsAt),endsAt=new Date(dto.endsAt);if(endsAt<=startsAt)throw new BadRequestException('Shift end must be after start.');const row=await this.prisma.scheduleEntry.create({data:{shopId,membershipId:dto.membershipId,jobRoleId:dto.jobRoleId,startsAt,endsAt,note:dto.note,createdById:actor.sub}});await this.record(actor,'workforce.schedule.create','Scheduled shift',{scheduleEntryId:row.id,membershipId:row.membershipId,startsAt,endsAt});return row;}
  async myShift(actor:JwtAccessPayload){const shopId=requireShopId(actor),membership=await this.requireActorMembership(actor),now=new Date();const [openPunch,schedule]=await Promise.all([this.prisma.timePunch.findFirst({where:{shopId,membershipId:membership.id,endedAt:null},orderBy:{startedAt:'desc'}}),this.prisma.scheduleEntry.findFirst({where:{shopId,membershipId:membership.id,status:'SCHEDULED',startsAt:{lte:new Date(now.getTime()+12*3600000)},endsAt:{gte:new Date(now.getTime()-12*3600000)}},orderBy:{startsAt:'asc'}})]);const openBreak=openPunch?await this.prisma.breakRecord.findFirst({where:{shopId,timePunchId:openPunch.id,endedAt:null},orderBy:{startedAt:'desc'}}):null;return {membership:{id:membership.id,name:membership.user.name??membership.user.email},schedule,openPunch,openBreak};}
  async clockIn(actor:JwtAccessPayload,dto:ClockInDto){const shopId=requireShopId(actor),membership=await this.requireActorMembership(actor),now=new Date();const punch=await this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`workforce:${shopId}:${membership.id}`}))`;const open=await tx.timePunch.findFirst({where:{shopId,membershipId:membership.id,endedAt:null}});if(open)throw new ConflictException('You are already clocked in.');const schedule=dto.scheduleEntryId?await tx.scheduleEntry.findFirst({where:{id:dto.scheduleEntryId,shopId,membershipId:membership.id}}):await tx.scheduleEntry.findFirst({where:{shopId,membershipId:membership.id,status:'SCHEDULED',startsAt:{lte:new Date(now.getTime()+4*3600000)},endsAt:{gte:now}},orderBy:{startsAt:'asc'}});const jobRoleId=dto.jobRoleId??schedule?.jobRoleId;if(!jobRoleId)throw new BadRequestException('Choose a job role or clock in from a scheduled shift.');const role=await tx.jobRole.findFirst({where:{id:jobRoleId,shopId,active:true}});if(!role)throw new NotFoundException('Job role not found.');const rate=await tx.employeeRate.findFirst({where:{shopId,membershipId:membership.id,jobRoleId,effectiveFrom:{lte:now},OR:[{effectiveTo:null},{effectiveTo:{gt:now}}]},orderBy:{effectiveFrom:'desc'}});if(!rate)throw new ConflictException('No effective wage rate exists for this employee and job role.');return tx.timePunch.create({data:{shopId,membershipId:membership.id,scheduleEntryId:schedule?.id,jobRoleId,employeeRateId:rate.id,hourlyRateMinor:rate.hourlyRateMinor,currency:rate.currency,startedAt:now}});});await this.record(actor,'workforce.clock-in','Clocked in',{timePunchId:punch.id,membershipId:membership.id});return punch;}
  async startBreak(actor:JwtAccessPayload,dto:StartBreakDto){const shopId=requireShopId(actor),membership=await this.requireActorMembership(actor);const punch=await this.openPunch(shopId,membership.id);const open=await this.prisma.breakRecord.findFirst({where:{shopId,timePunchId:punch.id,endedAt:null}});if(open)throw new ConflictException('A break is already active.');const row=await this.prisma.breakRecord.create({data:{shopId,timePunchId:punch.id,startedAt:new Date(),paid:dto.paid??false,note:dto.note}});await this.record(actor,'workforce.break.start','Started break',{timePunchId:punch.id,breakRecordId:row.id,paid:row.paid});return row;}
  async endBreak(actor:JwtAccessPayload){const shopId=requireShopId(actor),membership=await this.requireActorMembership(actor),punch=await this.openPunch(shopId,membership.id);const row=await this.prisma.breakRecord.findFirst({where:{shopId,timePunchId:punch.id,endedAt:null},orderBy:{startedAt:'desc'}});if(!row)throw new ConflictException('No active break.');const updated=await this.prisma.breakRecord.update({where:{id:row.id},data:{endedAt:new Date()}});await this.record(actor,'workforce.break.end','Ended break',{timePunchId:punch.id,breakRecordId:row.id});return updated;}
  async clockOut(actor:JwtAccessPayload){const shopId=requireShopId(actor),membership=await this.requireActorMembership(actor),punch=await this.openPunch(shopId,membership.id);const openBreak=await this.prisma.breakRecord.findFirst({where:{shopId,timePunchId:punch.id,endedAt:null}});if(openBreak)throw new ConflictException('End the active break before clocking out.');const updated=await this.prisma.timePunch.update({where:{id:punch.id},data:{endedAt:new Date()}});await this.record(actor,'workforce.clock-out','Clocked out',{timePunchId:punch.id,membershipId:membership.id});return updated;}
  async requestAdjustment(actor:JwtAccessPayload,dto:CreateTimeAdjustmentDto){const shopId=requireShopId(actor),membership=await this.requireActorMembership(actor);const punch=await this.prisma.timePunch.findFirst({where:{id:dto.timePunchId,shopId}});if(!punch)throw new NotFoundException('Time punch not found.');const isManager=this.hasStaffWrite(actor);if(punch.membershipId!==membership.id&&!isManager)throw new ForbiddenException('You can only request an adjustment for your own punch.');if(!dto.proposedStartedAt&&!dto.proposedEndedAt&&dto.proposedUnpaidBreakSeconds==null)throw new BadRequestException('Adjustment must change time or unpaid break seconds.');const row=await this.prisma.timeAdjustment.create({data:{shopId,timePunchId:punch.id,proposedStartedAt:dto.proposedStartedAt?new Date(dto.proposedStartedAt):undefined,proposedEndedAt:dto.proposedEndedAt?new Date(dto.proposedEndedAt):undefined,proposedUnpaidBreakSeconds:dto.proposedUnpaidBreakSeconds,reason:dto.reason,requestedById:actor.sub}});await this.record(actor,'workforce.adjustment.request','Requested time adjustment',{timeAdjustmentId:row.id,timePunchId:punch.id,reason:dto.reason});return row;}
  async pendingAdjustments(actor:JwtAccessPayload){return this.prisma.timeAdjustment.findMany({where:{shopId:requireShopId(actor),status:'PENDING'},orderBy:{createdAt:'asc'}});}
  async decideAdjustment(actor:JwtAccessPayload,id:string,dto:DecideTimeAdjustmentDto){const shopId=requireShopId(actor);const adjustment=await this.prisma.timeAdjustment.findFirst({where:{id,shopId,status:'PENDING'}});if(!adjustment)throw new NotFoundException('Pending adjustment not found.');const punch=await this.prisma.timePunch.findFirst({where:{id:adjustment.timePunchId,shopId}});if(!punch)throw new NotFoundException('Time punch not found.');if(dto.approve){const current=await this.effectivePunch(shopId,punch.id);const proposedStart=adjustment.proposedStartedAt??current.startedAt,proposedEnd=adjustment.proposedEndedAt??current.endedAt;if(!proposedEnd||proposedEnd<=proposedStart)throw new BadRequestException('Adjusted clock-out must be after clock-in.');await this.assertNoOverlap(shopId,punch.membershipId,punch.id,proposedStart,proposedEnd);}const row=await this.prisma.timeAdjustment.update({where:{id},data:{status:dto.approve?'APPROVED':'REJECTED',decidedById:actor.sub,decisionNote:dto.note,decidedAt:new Date()}});await this.record(actor,dto.approve?'workforce.adjustment.approve':'workforce.adjustment.reject',dto.approve?'Approved time adjustment':'Rejected time adjustment',{timeAdjustmentId:id,timePunchId:punch.id,reason:adjustment.reason,decisionNote:dto.note});return row;}
  async timeRecords(actor:JwtAccessPayload,from?:Date,to?:Date){const shopId=requireShopId(actor);const rows=await this.loadTimeRecords(shopId,from,to);if(this.canLaborCostAccess(actor))return rows;return rows.map(({hourlyRateMinor: _rate,currency: _currency,laborCostMinor: _cost,...safe})=>safe);}
  async report(actor:JwtAccessPayload,from:Date,to:Date){const full=await this.buildReport(actor,from,to);if(this.canLaborCostAccess(actor))return full;return {from:full.from,to:full.to,rows:full.rows.map(({laborCostMinor: _cost,...row})=>row),totals:{scheduledSeconds:full.totals.scheduledSeconds,workedSeconds:full.totals.workedSeconds}};}
  async laborAnalytics(actor:JwtAccessPayload,days=30){this.assertLaborCostAccess(actor);const shopId=requireShopId(actor);const since=new Date(Date.now()-Math.max(1,Math.min(days,365))*86400000);const report=await this.buildReport(actor,since,new Date());const revenue=await computeRevenueSince(this.prisma,shopId,since);const laborHours=report.totals.workedSeconds/3600;return {days,revenue,laborHours,laborCostMinor:report.totals.laborCostMinor,revenuePerLaborHour:laborHours>0?revenue/laborHours:0};}
  private async buildReport(actor:JwtAccessPayload,from:Date,to:Date){const shopId=requireShopId(actor);if(to<=from)throw new BadRequestException('Report end must be after start.');const [schedule,punches,memberships]=await Promise.all([this.prisma.scheduleEntry.findMany({where:{shopId,startsAt:{lt:to},endsAt:{gt:from},status:{not:'CANCELED'}}}),this.loadTimeRecords(shopId,from,to),this.prisma.membership.findMany({where:{shopId},include:{user:true}})]);const rows=memberships.map(m=>{const scheduledSeconds=schedule.filter(s=>s.membershipId===m.id).reduce((sum,s)=>sum+Math.max(0,Math.floor((s.endsAt.getTime()-s.startsAt.getTime())/1000)),0);const work=punches.filter(p=>p.membershipId===m.id);const workedSeconds=work.reduce((s,p)=>s+p.workedSeconds,0);const laborCostMinor=work.reduce((s,p)=>s+p.laborCostMinor,0);return {membershipId:m.id,name:m.user.name??m.user.email,scheduledSeconds,workedSeconds,laborCostMinor};});return {from,to,rows,totals:{scheduledSeconds:rows.reduce((s,r)=>s+r.scheduledSeconds,0),workedSeconds:rows.reduce((s,r)=>s+r.workedSeconds,0),laborCostMinor:rows.reduce((s,r)=>s+r.laborCostMinor,0)}};}
  private async loadTimeRecords(shopId:string,from?:Date,to?:Date){const where:any={shopId};if(from||to)where.startedAt={...(from?{gte:from}:{}),...(to?{lt:to}:{})};const punches=await this.prisma.timePunch.findMany({where,orderBy:{startedAt:'desc'},take:500});return Promise.all(punches.map(p=>this.effectivePunch(shopId,p.id)));}
  private async effectivePunch(shopId:string,punchId:string):Promise<EffectivePunch>{const punch=await this.prisma.timePunch.findFirst({where:{id:punchId,shopId}});if(!punch)throw new NotFoundException('Time punch not found.');const [breaks,adjustment]=await Promise.all([this.prisma.breakRecord.findMany({where:{shopId,timePunchId:punch.id,paid:false,endedAt:{not:null}}}),this.prisma.timeAdjustment.findFirst({where:{shopId,timePunchId:punch.id,status:'APPROVED'},orderBy:{decidedAt:'desc'}})]);const startedAt=adjustment?.proposedStartedAt??punch.startedAt,endedAt=adjustment?.proposedEndedAt??punch.endedAt;const rawUnpaid=breaks.reduce((s,b)=>s+(b.endedAt?Math.max(0,Math.floor((b.endedAt.getTime()-b.startedAt.getTime())/1000)):0),0);const unpaidBreakSeconds=adjustment?.proposedUnpaidBreakSeconds??rawUnpaid;const workedSeconds=endedAt?calculateWorkedSeconds({startedAt,endedAt,unpaidBreakSeconds}):0;return {id:punch.id,membershipId:punch.membershipId,startedAt,endedAt,unpaidBreakSeconds,workedSeconds,hourlyRateMinor:punch.hourlyRateMinor,currency:punch.currency,laborCostMinor:calculateLaborCostMinor(workedSeconds,punch.hourlyRateMinor)};}
  private async assertNoOverlap(shopId:string,membershipId:string,excludeId:string,start:Date,end:Date){const others=await this.prisma.timePunch.findMany({where:{shopId,membershipId,id:{not:excludeId}}});for(const p of others){const effective=await this.effectivePunch(shopId,p.id);if(effective.endedAt&&intervalsOverlap(start,end,effective.startedAt,effective.endedAt))throw new ConflictException('Approved adjustment would overlap another time punch.');}}
  private async openPunch(shopId:string,membershipId:string){const p=await this.prisma.timePunch.findFirst({where:{shopId,membershipId,endedAt:null},orderBy:{startedAt:'desc'}});if(!p)throw new ConflictException('You are not clocked in.');return p;}
  private async requireActorMembership(actor:JwtAccessPayload){const shopId=requireShopId(actor);const m=await this.prisma.membership.findFirst({where:{shopId,userId:actor.sub},include:{user:true}});if(!m)throw new ForbiddenException('Active venue membership required.');return m;}
  private async requireMembership(shopId:string,id:string){const m=await this.prisma.membership.findFirst({where:{id,shopId}});if(!m)throw new NotFoundException('Employee membership not found.');return m;}
  private async requireRole(shopId:string,id:string){const r=await this.prisma.jobRole.findFirst({where:{id,shopId,active:true}});if(!r)throw new NotFoundException('Job role not found.');return r;}
  private hasStaffWrite(actor:JwtAccessPayload){const p=actor.perms??'';return p==='*'||p.split(',').map(x=>x.trim()).includes('staff.write');}
  private canLaborCostAccess(actor:JwtAccessPayload){return actor.shopRole==='OWNER'||actor.sysRole==='SUPER_ADMIN';}
  private assertLaborCostAccess(actor:JwtAccessPayload){if(!this.canLaborCostAccess(actor))throw new ForbiddenException('Labor cost analytics is restricted to venue owners.');}
  private record(actor:JwtAccessPayload,action:string,summary:string,meta:Record<string,unknown>){return this.audit.record(actor,{section:'operations',action,summary,meta});}
}
