import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { requireShopId } from '../../common/tenant';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import type { JwtAccessPayload } from '../auth/auth.service';
import { CreatePrepRouteDto, CreatePrepStationDto, PrepStatusDto } from './dto/kitchen.dto';

const TERMINAL = new Set(['COLLECTED','CANCELED']);
const TRANSITIONS: Record<string,string[]> = { NEW:['PREPARING','CANCELED'], PREPARING:['READY','CANCELED'], READY:['COLLECTED','CANCELED'], COLLECTED:[], CANCELED:[] };
export function isPrepTransitionAllowed(from:string,to:string){return from===to || (TRANSITIONS[from]??[]).includes(to);}
export function projectTicketStatus(statuses:string[]){const live=statuses.filter(Boolean);if(!live.length)return 'CANCELED';if(live.every(s=>s==='CANCELED'))return 'CANCELED';if(live.every(s=>s==='COLLECTED'||s==='CANCELED'))return 'COLLECTED';if(live.every(s=>s==='READY'||s==='COLLECTED'||s==='CANCELED'))return 'READY';if(live.some(s=>s==='PREPARING'||s==='READY'||s==='COLLECTED'))return 'PREPARING';return 'NEW';}
export function buildEdgePrepRelay(ticket:{id:string;stationId:string;status:string;updatedAt:Date},lines:{id:string;status:string;quantity:number}[]){return {kind:'KDS_PROJECTION',ticketId:ticket.id,stationId:ticket.stationId,status:ticket.status,updatedAt:ticket.updatedAt.toISOString(),lines:lines.map(l=>({id:l.id,status:l.status,quantity:l.quantity}))};}
export function buildPrepAlerts(tickets:{id:string;stationId:string;status:string;ageSeconds:number}[],stations:{id:string;targetSeconds:number}[]){const targets=new Map(stations.map(station=>[station.id,station.targetSeconds]));const alerts:{kind:'READY'|'OVERDUE';ticketId:string;stationId:string}[]=[];for(const ticket of tickets){if(ticket.status==='READY'){alerts.push({kind:'READY',ticketId:ticket.id,stationId:ticket.stationId});continue;}const target=targets.get(ticket.stationId);if(target!=null&&(ticket.status==='NEW'||ticket.status==='PREPARING')&&ticket.ageSeconds>target)alerts.push({kind:'OVERDUE',ticketId:ticket.id,stationId:ticket.stationId});}return alerts;}
function routeKey(snapshot:Prisma.JsonValue):string|null{if(!snapshot||typeof snapshot!=='object'||Array.isArray(snapshot))return null;const value=(snapshot as Prisma.JsonObject).prepRouteKey;return typeof value==='string'&&value.trim()?value:null;}

@Injectable()
export class KitchenService {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
  listStations(actor:JwtAccessPayload){return this.prisma.prepStation.findMany({where:{shopId:requireShopId(actor),active:true},orderBy:{sortOrder:'asc'}});}
  async createStation(actor:JwtAccessPayload,dto:CreatePrepStationDto){const row=await this.prisma.prepStation.create({data:{shopId:requireShopId(actor),name:dto.name,kind:dto.kind,targetSeconds:dto.targetSeconds??600,sortOrder:dto.sortOrder??0}});await this.record(actor,'kds.station.create','Created prep station',{stationId:row.id,kind:row.kind});return row;}
  async createRoute(actor:JwtAccessPayload,dto:CreatePrepRouteDto){const shopId=requireShopId(actor);const station=await this.prisma.prepStation.findFirst({where:{id:dto.stationId,shopId,active:true}});if(!station)throw new NotFoundException('Prep station not found.');return this.prisma.prepRoute.upsert({where:{shopId_key:{shopId,key:dto.key}},create:{shopId,key:dto.key,stationId:dto.stationId,menuItemId:dto.menuItemId,priority:dto.priority??0},update:{stationId:dto.stationId,menuItemId:dto.menuItemId,priority:dto.priority??0,active:true}});}
  async submitOrder(actor:JwtAccessPayload,orderId:string){const shopId=requireShopId(actor);const count=await this.routeOrder(shopId,orderId);await this.record(actor,'kds.order.route','Routed order to prep stations',{orderId,ticketCount:count});return {ok:true,ticketCount:count};}
  async board(actor:JwtAccessPayload,stationId?:string){const shopId=requireShopId(actor);await this.routePendingOrders(shopId);await this.syncCanceledOrderLines(shopId);const tickets=await this.prisma.prepTicket.findMany({where:{shopId,...(stationId?{stationId}:{}),status:{in:['NEW','PREPARING','READY']}},orderBy:{openedAt:'asc'}});const stations=await this.prisma.prepStation.findMany({where:{shopId,active:true},orderBy:{sortOrder:'asc'}});const lines=tickets.length?await this.prisma.prepTicketLine.findMany({where:{shopId,ticketId:{in:tickets.map(t=>t.id)}},orderBy:{routedAt:'asc'}}):[];const now=Date.now();const projectedTickets=tickets.map(t=>{const ticketLines=lines.filter(l=>l.ticketId===t.id);return {...t,ageSeconds:Math.max(0,Math.floor((now-t.openedAt.getTime())/1000)),prepareSeconds:t.startedAt?Math.max(0,Math.floor(((t.readyAt??new Date()).getTime()-t.startedAt.getTime())/1000)):null,lines:ticketLines,edgeProjection:buildEdgePrepRelay(t,ticketLines)};});return {generatedAt:new Date(),stations,tickets:projectedTickets,alerts:buildPrepAlerts(projectedTickets,stations)};}
  async setLineStatus(actor:JwtAccessPayload,lineId:string,dto:PrepStatusDto){const shopId=requireShopId(actor);const line=await this.prisma.prepTicketLine.findFirst({where:{id:lineId,shopId}});if(!line)throw new NotFoundException('Prep line not found.');if(!isPrepTransitionAllowed(line.status,dto.status))throw new ConflictException(`Invalid prep transition ${line.status} → ${dto.status}.`);if(line.status===dto.status)return line;const now=new Date();const data:Prisma.PrepTicketLineUpdateInput={status:dto.status,...(dto.status==='PREPARING'?{startedAt:line.startedAt??now}:{}),...(dto.status==='READY'?{readyAt:now}:{}),...(dto.status==='COLLECTED'?{collectedAt:now}:{}),...(dto.status==='CANCELED'?{canceledAt:now,cancellationReason:dto.reason??'KDS'}:{})};const updated=await this.prisma.$transaction(async tx=>{const row=await tx.prepTicketLine.update({where:{id:line.id},data});await tx.prepStatusEvent.create({data:{shopId,ticketId:line.ticketId,lineId:line.id,fromStatus:line.status,toStatus:dto.status,actorUserId:actor.sub,reason:dto.reason}});if(dto.status==='CANCELED')await tx.venueOrderLine.updateMany({where:{id:line.orderLineId,shopId,canceledAt:null},data:{canceledAt:now,cancellationReason:dto.reason??'KDS'}});return row;});await this.updateTicketProjection(shopId,line.ticketId,actor.sub,dto.reason);return updated;}
  async setTicketStatus(actor:JwtAccessPayload,ticketId:string,dto:PrepStatusDto){const shopId=requireShopId(actor);const ticket=await this.prisma.prepTicket.findFirst({where:{id:ticketId,shopId}});if(!ticket)throw new NotFoundException('Prep ticket not found.');const lines=await this.prisma.prepTicketLine.findMany({where:{shopId,ticketId}});for(const line of lines){if(TERMINAL.has(line.status))continue;if(!isPrepTransitionAllowed(line.status,dto.status)){if(dto.status==='READY'&&line.status==='NEW')await this.setLineStatus(actor,line.id,{status:'PREPARING'});else if(dto.status==='COLLECTED'&&line.status!=='READY'){if(line.status==='NEW')await this.setLineStatus(actor,line.id,{status:'PREPARING'});await this.setLineStatus(actor,line.id,{status:'READY'});}}await this.setLineStatus(actor,line.id,dto);}return this.prisma.prepTicket.findUnique({where:{id:ticketId}});}
  private async routePendingOrders(shopId:string){const orders=await this.prisma.venueOrder.findMany({where:{shopId,status:{in:['OPEN','SENT']}},select:{id:true},take:100,orderBy:{createdAt:'asc'}});for(const order of orders)await this.routeOrder(shopId,order.id);}
  private async routeOrder(shopId:string,orderId:string){const order=await this.prisma.venueOrder.findFirst({where:{id:orderId,shopId,status:{in:['OPEN','SENT']}}});if(!order)throw new NotFoundException('Order not found or not routable.');const lines=await this.prisma.venueOrderLine.findMany({where:{shopId,orderId,canceledAt:null}});const modifiers=lines.length?await this.prisma.orderLineModifier.findMany({where:{shopId,orderLineId:{in:lines.map(l=>l.id)}}}):[];const routed=new Set<string>();for(const line of lines){const key=routeKey(line.priceSnapshot);if(!key)continue;const route=await this.prisma.prepRoute.findFirst({where:{shopId,key,active:true}});if(!route)continue;const station=await this.prisma.prepStation.findFirst({where:{id:route.stationId,shopId,active:true}});if(!station)continue;const ticket=await this.prisma.prepTicket.upsert({where:{shopId_orderId_stationId:{shopId,orderId,stationId:station.id}},create:{shopId,orderId,stationId:station.id},update:{}});await this.prisma.prepTicketLine.upsert({where:{shopId_orderLineId_stationId:{shopId,orderLineId:line.id,stationId:station.id}},create:{shopId,ticketId:ticket.id,stationId:station.id,orderLineId:line.id,quantity:line.quantity,nameSnapshot:line.nameSnapshot,modifiersSnapshot:modifiers.filter(m=>m.orderLineId===line.id).map(m=>({name:m.nameSnapshot,priceDeltaMinor:m.priceDeltaMinor})) as Prisma.InputJsonValue},update:{}});routed.add(ticket.id);}if(routed.size&&order.status==='OPEN')await this.prisma.venueOrder.update({where:{id:order.id},data:{status:'SENT'}});return routed.size;}
  private async syncCanceledOrderLines(shopId:string){const canceled=await this.prisma.venueOrderLine.findMany({where:{shopId,canceledAt:{not:null}},select:{id:true,canceledAt:true,cancellationReason:true}});if(!canceled.length)return;for(const line of canceled)await this.prisma.prepTicketLine.updateMany({where:{shopId,orderLineId:line.id,status:{notIn:['COLLECTED','CANCELED']}},data:{status:'CANCELED',canceledAt:line.canceledAt,cancellationReason:line.cancellationReason??'ORDER_CANCELED'}});}
  private async updateTicketProjection(shopId:string,ticketId:string,actorUserId:string,reason?:string){const ticket=await this.prisma.prepTicket.findFirst({where:{id:ticketId,shopId}});if(!ticket)return;const lines=await this.prisma.prepTicketLine.findMany({where:{shopId,ticketId}});const next=projectTicketStatus(lines.map(l=>l.status));if(next===ticket.status)return;const now=new Date();await this.prisma.$transaction(async tx=>{await tx.prepTicket.update({where:{id:ticketId},data:{status:next,...(next==='PREPARING'?{startedAt:ticket.startedAt??now}:{}),...(next==='READY'?{readyAt:now}:{}),...(next==='COLLECTED'?{collectedAt:now}:{}),...(next==='CANCELED'?{canceledAt:now}:{})}});await tx.prepStatusEvent.create({data:{shopId,ticketId,fromStatus:ticket.status,toStatus:next,actorUserId,reason}});});}
  private record(actor:JwtAccessPayload,action:string,summary:string,meta:Record<string,unknown>){return this.audit.record(actor,{section:'operations',action,summary,meta});}
}
