import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { requireShopId } from '../../common/tenant';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import type { JwtAccessPayload } from '../auth/auth.service';
import { CreateLegacyInventoryMappingDto, CreateLocationDto, CreatePurchaseOrderDto, CreateRecipeDto, CreateStockItemDto, CreateSupplierDto, InventoryProfileDto, PostStocktakeDto, ReceiveDto, ReverseConsumptionDto, StockMovementDto, TransferDto } from './dto/inventory.dto';

type InventoryDb = PrismaService | Prisma.TransactionClient;
export function projectBalanceMilli(movements:{quantityMilli:number}[]){return movements.reduce((s,m)=>s+m.quantityMilli,0);}
export function weightedAverageCostMinor(input:{currentMilli:number;currentCostMinor:number;receivedMilli:number;receivedCostMinor:number}){const current=Math.max(0,input.currentMilli);const total=current+input.receivedMilli;if(total<=0)return input.receivedCostMinor;return Math.max(0,Math.round((current*input.currentCostMinor+input.receivedMilli*input.receivedCostMinor)/total));}
export function movementTotalCostMinor(quantityMilli:number,unitCostMinor:number){return Math.round((Math.abs(quantityMilli)*unitCostMinor)/1000);}
export function recipeConsumptionMilli(componentQuantityMilli:number,orderedQuantity:number,yieldMilli:number){if(yieldMilli<=0)throw new BadRequestException('Recipe yield must be greater than zero.');return -Math.round((componentQuantityMilli*orderedQuantity*1000)/yieldMilli);}

@Injectable()
export class InventoryV2Service {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService){}
  async profile(actor:JwtAccessPayload){const shopId=requireShopId(actor);return (await this.prisma.inventoryProfile.findUnique({where:{shopId}}))??{shopId,enabled:false,legacyDualMode:true};}
  async setProfile(actor:JwtAccessPayload,dto:InventoryProfileDto){const shopId=requireShopId(actor);const row=await this.prisma.inventoryProfile.upsert({where:{shopId},create:{shopId,enabled:dto.enabled,legacyDualMode:dto.legacyDualMode??true},update:{enabled:dto.enabled,legacyDualMode:dto.legacyDualMode??true}});await this.record(actor,'inventory.profile.update','Updated inventory mode',{enabled:row.enabled,legacyDualMode:row.legacyDualMode});return row;}
  async dashboard(actor:JwtAccessPayload){const shopId=requireShopId(actor);const [profile,locations,items,movements,legacyMappings]=await Promise.all([this.profile(actor),this.prisma.inventoryLocation.findMany({where:{shopId,active:true},orderBy:{name:'asc'}}),this.prisma.stockItem.findMany({where:{shopId,active:true},orderBy:{name:'asc'}}),this.prisma.stockMovement.findMany({where:{shopId},orderBy:{occurredAt:'asc'}}),this.prisma.legacyInventoryMapping.findMany({where:{shopId},orderBy:{createdAt:'asc'}})]);return {profile,locations,legacyMappings,items:items.map(item=>({...item,byLocation:locations.map(location=>({locationId:location.id,locationName:location.name,balanceMilli:projectBalanceMilli(movements.filter(m=>m.stockItemId===item.id&&m.locationId===location.id))})),balanceMilli:projectBalanceMilli(movements.filter(m=>m.stockItemId===item.id))}))};}
  createLocation(actor:JwtAccessPayload,dto:CreateLocationDto){return this.prisma.inventoryLocation.create({data:{shopId:requireShopId(actor),name:dto.name}});}
  createStockItem(actor:JwtAccessPayload,dto:CreateStockItemDto){return this.prisma.stockItem.create({data:{shopId:requireShopId(actor),name:dto.name,sku:dto.sku,categoryId:dto.categoryId,unit:dto.unit??'unit'}});}
  createSupplier(actor:JwtAccessPayload,dto:CreateSupplierDto){return this.prisma.supplier.create({data:{shopId:requireShopId(actor),...dto}});}
  async createRecipe(actor:JwtAccessPayload,dto:CreateRecipeDto){const shopId=requireShopId(actor);const yieldMilli=dto.yieldMilli??1000;if(yieldMilli<=0)throw new BadRequestException('Recipe yield must be greater than zero.');for(const component of dto.components)await this.requireItem(shopId,component.stockItemId);return this.prisma.$transaction(async tx=>{const recipe=await tx.recipe.create({data:{shopId,key:dto.key,name:dto.name,menuItemId:dto.menuItemId,yieldMilli}});await tx.recipeComponent.createMany({data:dto.components.map(c=>({shopId,recipeId:recipe.id,stockItemId:c.stockItemId,quantityMilli:c.quantityMilli}))});if(dto.menuItemId)await tx.menuItemCommerceProfile.upsert({where:{shopId_menuItemId:{shopId,menuItemId:dto.menuItemId}},create:{shopId,menuItemId:dto.menuItemId,recipeKey:dto.key},update:{recipeKey:dto.key}});return recipe;});}
  async createLegacyMapping(actor:JwtAccessPayload,dto:CreateLegacyInventoryMappingDto){const shopId=requireShopId(actor);const menuItem=await this.prisma.menuItem.findFirst({where:{id:dto.menuItemId,shopId}});if(!menuItem)throw new NotFoundException('Legacy menu item not found.');const item=await this.requireItem(shopId,dto.stockItemId);const existing=await this.prisma.legacyInventoryMapping.findUnique({where:{shopId_menuItemId:{shopId,menuItemId:dto.menuItemId}}});if(existing?.migratedAt&&existing.stockItemId!==dto.stockItemId)throw new ConflictException('A migrated legacy item cannot be remapped; reverse/open a new migration explicitly instead.');if(dto.seedOpeningBalance&&!dto.locationId)throw new BadRequestException('locationId is required when seeding legacy opening stock.');const mapping=await this.prisma.$transaction(async tx=>{await this.lockInventory(tx,shopId);if(dto.locationId)await this.requireLocation(shopId,dto.locationId,tx);const row=await tx.legacyInventoryMapping.upsert({where:{shopId_menuItemId:{shopId,menuItemId:dto.menuItemId}},create:{shopId,menuItemId:dto.menuItemId,stockItemId:item.id,locationId:dto.locationId,createdById:actor.sub},update:{stockItemId:item.id,locationId:dto.locationId}});if(dto.seedOpeningBalance&&dto.locationId){const quantityMilli=menuItem.stock*1000;if(quantityMilli!==0)await tx.stockMovement.upsert({where:{movementKey:`legacy-opening:${menuItem.id}`},create:{shopId,stockItemId:item.id,locationId:dto.locationId,kind:'LEGACY_OPENING',quantityMilli,unitCostMinor:item.weightedAverageCostMinor,totalCostMinor:movementTotalCostMinor(quantityMilli,item.weightedAverageCostMinor),referenceType:'MENU_ITEM',referenceId:menuItem.id,movementKey:`legacy-opening:${menuItem.id}`,note:'Opening balance migrated from MenuItem.stock',actorUserId:actor.sub},update:{}});return tx.legacyInventoryMapping.update({where:{id:row.id},data:{migratedAt:new Date()}});}return row;});await this.record(actor,'inventory.legacy.map','Mapped legacy menu stock to Inventory 2.0',{mappingId:mapping.id,menuItemId:menuItem.id,stockItemId:item.id,seedOpeningBalance:dto.seedOpeningBalance===true});return mapping;}
  async waste(actor:JwtAccessPayload,dto:StockMovementDto){const shopId=requireShopId(actor);if(dto.quantityMilli===0)throw new BadRequestException('Waste quantity cannot be zero.');const quantity=-Math.abs(dto.quantityMilli);const row=await this.prisma.$transaction(async tx=>{await this.lockInventory(tx,shopId);const item=await this.requireItem(shopId,dto.stockItemId,tx);await this.requireLocation(shopId,dto.locationId,tx);const available=await this.balance(shopId,item.id,dto.locationId,tx);if(available<Math.abs(quantity))throw new ConflictException('Waste quantity exceeds available stock.');return tx.stockMovement.create({data:{shopId,stockItemId:item.id,locationId:dto.locationId,kind:'WASTE',quantityMilli:quantity,unitCostMinor:item.weightedAverageCostMinor,totalCostMinor:movementTotalCostMinor(quantity,item.weightedAverageCostMinor),movementKey:`waste:${randomUUID()}`,note:dto.note,actorUserId:actor.sub}});});await this.record(actor,'inventory.waste','Posted waste movement',{movementId:row.id,stockItemId:row.stockItemId,quantityMilli:quantity});return row;}
  async createPurchaseOrder(actor:JwtAccessPayload,dto:CreatePurchaseOrderDto){const shopId=requireShopId(actor);await this.requireLocation(shopId,dto.locationId);const supplier=await this.prisma.supplier.findFirst({where:{id:dto.supplierId,shopId,active:true}});if(!supplier)throw new NotFoundException('Supplier not found.');for(const line of dto.lines)await this.requireItem(shopId,line.stockItemId);return this.prisma.$transaction(async tx=>{const po=await tx.purchaseOrder.create({data:{shopId,supplierId:dto.supplierId,locationId:dto.locationId,status:'ORDERED',orderedAt:new Date(),createdById:actor.sub}});await tx.purchaseOrderLine.createMany({data:dto.lines.map(l=>({shopId,purchaseOrderId:po.id,stockItemId:l.stockItemId,orderedMilli:l.orderedMilli,unitCostMinor:l.unitCostMinor}))});return po;});}
  async receive(actor:JwtAccessPayload,dto:ReceiveDto,purchaseOrderId?:string){const shopId=requireShopId(actor);await this.requireLocation(shopId,dto.locationId);if(purchaseOrderId){const po=await this.prisma.purchaseOrder.findFirst({where:{id:purchaseOrderId,shopId}});if(!po)throw new NotFoundException('Purchase order not found.');}for(const line of dto.lines)await this.requireItem(shopId,line.stockItemId);const receipt=await this.prisma.$transaction(async tx=>{await this.lockInventory(tx,shopId);const gr=await tx.goodsReceipt.create({data:{shopId,purchaseOrderId,supplierId:dto.supplierId,locationId:dto.locationId,receivedById:actor.sub}});for(const line of dto.lines){const item=await this.requireItem(shopId,line.stockItemId,tx);const prior=await tx.stockMovement.aggregate({where:{shopId,stockItemId:item.id},_sum:{quantityMilli:true}});const currentMilli=prior._sum.quantityMilli??0;const nextCost=weightedAverageCostMinor({currentMilli,currentCostMinor:item.weightedAverageCostMinor,receivedMilli:line.quantityMilli,receivedCostMinor:line.unitCostMinor});const grLine=await tx.goodsReceiptLine.create({data:{shopId,goodsReceiptId:gr.id,stockItemId:item.id,quantityMilli:line.quantityMilli,unitCostMinor:line.unitCostMinor}});await tx.stockMovement.create({data:{shopId,stockItemId:item.id,locationId:dto.locationId,kind:'RECEIPT',quantityMilli:line.quantityMilli,unitCostMinor:line.unitCostMinor,totalCostMinor:movementTotalCostMinor(line.quantityMilli,line.unitCostMinor),referenceType:'GOODS_RECEIPT',referenceId:gr.id,movementKey:`receipt:${grLine.id}`,actorUserId:actor.sub}});await tx.stockItem.update({where:{id:item.id},data:{weightedAverageCostMinor:nextCost}});}if(purchaseOrderId)await tx.purchaseOrder.update({where:{id:purchaseOrderId},data:{status:'RECEIVED',closedAt:new Date()}});return gr;});await this.record(actor,'inventory.receive','Received stock',{goodsReceiptId:receipt.id,purchaseOrderId});return receipt;}
  async postStocktake(actor:JwtAccessPayload,dto:PostStocktakeDto){const shopId=requireShopId(actor);await this.requireLocation(shopId,dto.locationId);const result=await this.prisma.$transaction(async tx=>{await this.lockInventory(tx,shopId);const take=await tx.stocktake.create({data:{shopId,locationId:dto.locationId,countedById:actor.sub}});for(const line of dto.lines){const item=await this.requireItem(shopId,line.stockItemId,tx);const agg=await tx.stockMovement.aggregate({where:{shopId,stockItemId:item.id,locationId:dto.locationId},_sum:{quantityMilli:true}});const expectedMilli=agg._sum.quantityMilli??0;const adjustmentMilli=line.countedMilli-expectedMilli;await tx.stocktakeLine.create({data:{shopId,stocktakeId:take.id,stockItemId:item.id,countedMilli:line.countedMilli,expectedMilli,adjustmentMilli}});if(adjustmentMilli!==0)await tx.stockMovement.create({data:{shopId,stockItemId:item.id,locationId:dto.locationId,kind:'STOCKTAKE_ADJUSTMENT',quantityMilli:adjustmentMilli,unitCostMinor:item.weightedAverageCostMinor,totalCostMinor:movementTotalCostMinor(adjustmentMilli,item.weightedAverageCostMinor),referenceType:'STOCKTAKE',referenceId:take.id,movementKey:`stocktake:${take.id}:${item.id}`,actorUserId:actor.sub}});}return tx.stocktake.update({where:{id:take.id},data:{status:'POSTED',postedAt:new Date(),version:{increment:1}}});});await this.record(actor,'inventory.stocktake.post','Posted stocktake adjustments',{stocktakeId:result.id});return result;}
  async transfer(actor:JwtAccessPayload,dto:TransferDto){const shopId=requireShopId(actor);if(dto.fromLocationId===dto.toLocationId)throw new BadRequestException('Transfer locations must differ.');return this.prisma.$transaction(async tx=>{await this.lockInventory(tx,shopId);const item=await this.requireItem(shopId,dto.stockItemId,tx);await this.requireLocation(shopId,dto.fromLocationId,tx);await this.requireLocation(shopId,dto.toLocationId,tx);const available=await this.balance(shopId,item.id,dto.fromLocationId,tx);if(available<dto.quantityMilli)throw new ConflictException('Insufficient source stock.');const row=await tx.stockTransfer.create({data:{shopId,stockItemId:item.id,fromLocationId:dto.fromLocationId,toLocationId:dto.toLocationId,quantityMilli:dto.quantityMilli,actorUserId:actor.sub}});const cost=item.weightedAverageCostMinor;await tx.stockMovement.createMany({data:[{shopId,stockItemId:item.id,locationId:dto.fromLocationId,kind:'TRANSFER_OUT',quantityMilli:-dto.quantityMilli,unitCostMinor:cost,totalCostMinor:movementTotalCostMinor(dto.quantityMilli,cost),referenceType:'TRANSFER',referenceId:row.id,movementKey:`transfer:${row.id}:out`,actorUserId:actor.sub},{shopId,stockItemId:item.id,locationId:dto.toLocationId,kind:'TRANSFER_IN',quantityMilli:dto.quantityMilli,unitCostMinor:cost,totalCostMinor:movementTotalCostMinor(dto.quantityMilli,cost),referenceType:'TRANSFER',referenceId:row.id,movementKey:`transfer:${row.id}:in`,actorUserId:actor.sub}]});return row;});}
  async completeOrder(actor:JwtAccessPayload,orderId:string){const shopId=requireShopId(actor);const completed=await this.prisma.$transaction(async tx=>{await this.lockInventory(tx,shopId);const order=await tx.venueOrder.findFirst({where:{id:orderId,shopId}});if(!order)throw new NotFoundException('Order not found.');if(order.status==='COMPLETED')return order;if(order.status==='CANCELED'||order.status==='REFUNDED')throw new ConflictException('Canceled/refunded order cannot be completed.');const profile=(await tx.inventoryProfile.findUnique({where:{shopId}}))??{enabled:false,legacyDualMode:true};const lines=await tx.venueOrderLine.findMany({where:{shopId,orderId,canceledAt:null}});
    if(profile.legacyDualMode){for(const line of lines){const item=await tx.menuItem.findFirst({where:{id:line.menuItemId,shopId}});if(!item)throw new NotFoundException('Menu item not found while applying legacy stock.');if(!item.trackStock)continue;const changed=await tx.menuItem.updateMany({where:{id:item.id,shopId,trackStock:true,stock:{gte:line.quantity}},data:{stock:{decrement:line.quantity}}});if(changed.count!==1)throw new ConflictException(`Insufficient legacy stock for ${item.name}.`);}}
    if(profile.enabled){const location=await tx.inventoryLocation.findFirst({where:{shopId,active:true},orderBy:{createdAt:'asc'}});if(!location)throw new ConflictException('Inventory is enabled but no active location exists.');for(const line of lines){const commerce=await tx.menuItemCommerceProfile.findUnique({where:{shopId_menuItemId:{shopId,menuItemId:line.menuItemId}}});if(!commerce?.recipeKey)continue;const recipe=await tx.recipe.findUnique({where:{shopId_key:{shopId,key:commerce.recipeKey}}});if(!recipe?.active)continue;if(recipe.yieldMilli<=0)throw new ConflictException(`Recipe ${recipe.name} has an invalid yield.`);const components=await tx.recipeComponent.findMany({where:{shopId,recipeId:recipe.id}});for(const component of components){const item=await this.requireItem(shopId,component.stockItemId,tx);const quantity=recipeConsumptionMilli(component.quantityMilli,line.quantity,recipe.yieldMilli);const available=await this.balance(shopId,item.id,location.id,tx);if(available+quantity<0)throw new ConflictException(`Insufficient Inventory 2.0 stock for ${item.name}.`);await tx.stockMovement.upsert({where:{movementKey:`sale:${line.id}:${component.id}`},create:{shopId,stockItemId:item.id,locationId:location.id,kind:'SALE_CONSUMPTION',quantityMilli:quantity,unitCostMinor:item.weightedAverageCostMinor,totalCostMinor:movementTotalCostMinor(quantity,item.weightedAverageCostMinor),referenceType:'ORDER_LINE',referenceId:line.id,movementKey:`sale:${line.id}:${component.id}`,actorUserId:actor.sub},update:{}});}}}return tx.venueOrder.update({where:{id:orderId},data:{status:'COMPLETED',completedAt:new Date()}});});await this.record(actor,'inventory.order.complete','Completed order and atomically applied enabled stock accounting',{orderId});return completed;}
  async reverseOrder(actor:JwtAccessPayload,orderId:string,dto:ReverseConsumptionDto){const shopId=requireShopId(actor);const row=await this.prisma.$transaction(async tx=>{await this.lockInventory(tx,shopId);const order=await tx.venueOrder.findFirst({where:{id:orderId,shopId}});if(!order)throw new NotFoundException('Order not found.');if(order.status==='REFUNDED')return order;if(order.status!=='COMPLETED')throw new ConflictException('Only completed order consumption can be reversed.');const profile=(await tx.inventoryProfile.findUnique({where:{shopId}}))??{enabled:false,legacyDualMode:true};const lines=await tx.venueOrderLine.findMany({where:{shopId,orderId,canceledAt:null}});if(profile.legacyDualMode){for(const line of lines){const item=await tx.menuItem.findFirst({where:{id:line.menuItemId,shopId}});if(item?.trackStock)await tx.menuItem.update({where:{id:item.id},data:{stock:{increment:line.quantity}}});}}const lineIds=lines.map(l=>l.id);const originals=lineIds.length?await tx.stockMovement.findMany({where:{shopId,kind:'SALE_CONSUMPTION',referenceType:'ORDER_LINE',referenceId:{in:lineIds}}}):[];for(const m of originals)await tx.stockMovement.upsert({where:{movementKey:`reversal:${m.movementKey}`},create:{shopId,stockItemId:m.stockItemId,locationId:m.locationId,kind:'SALE_REVERSAL',quantityMilli:-m.quantityMilli,unitCostMinor:m.unitCostMinor,totalCostMinor:m.totalCostMinor,referenceType:'ORDER',referenceId:orderId,movementKey:`reversal:${m.movementKey}`,note:dto.reason,actorUserId:actor.sub},update:{}});return tx.venueOrder.update({where:{id:orderId},data:{status:'REFUNDED'}});});await this.record(actor,'inventory.order.reverse','Reversed enabled stock accounting',{orderId,reason:dto.reason});return row;}
  async cogs(actor:JwtAccessPayload){const shopId=requireShopId(actor);const movements=await this.prisma.stockMovement.findMany({where:{shopId,kind:{in:['SALE_CONSUMPTION','SALE_REVERSAL']}}});const cogsMinor=movements.reduce((sum,m)=>sum+(m.kind==='SALE_CONSUMPTION'?m.totalCostMinor:-m.totalCostMinor),0);const revenue=await this.prisma.venueOrder.aggregate({where:{shopId,status:'COMPLETED'},_sum:{subtotalMinor:true}});const revenueMinor=revenue._sum.subtotalMinor??0;return {revenueMinor,cogsMinor,grossMarginMinor:revenueMinor-cogsMinor,grossMarginPct:revenueMinor?((revenueMinor-cogsMinor)/revenueMinor)*100:0};}
  private async balance(shopId:string,itemId:string,locationId:string,db:InventoryDb=this.prisma){const agg=await db.stockMovement.aggregate({where:{shopId,stockItemId:itemId,locationId},_sum:{quantityMilli:true}});return agg._sum.quantityMilli??0;}
  private async requireItem(shopId:string,id:string,db:InventoryDb=this.prisma){const row=await db.stockItem.findFirst({where:{id,shopId,active:true}});if(!row)throw new NotFoundException('Stock item not found.');return row;}
  private async requireLocation(shopId:string,id:string,db:InventoryDb=this.prisma){const row=await db.inventoryLocation.findFirst({where:{id,shopId,active:true}});if(!row)throw new NotFoundException('Inventory location not found.');return row;}
  private lockInventory(tx:Prisma.TransactionClient,shopId:string){return tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`inventory:${shopId}`}))`;}
  private record(actor:JwtAccessPayload,action:string,summary:string,meta:Record<string,unknown>){return this.audit.record(actor,{section:'operations',action,summary,meta});}
}
