import { Type } from 'class-transformer';
import { ArrayMinSize, IsArray, IsBoolean, IsIn, IsInt, IsISO8601, IsOptional, IsString, Min, ValidateNested } from 'class-validator';
export const NEGATIVE_STOCK_POLICIES=['BLOCK','WARN_ALLOW','ALLOW_SELECTED','ALLOW_WITH_APPROVAL'] as const;
export const WASTE_REASONS=['SPOILAGE','BREAKAGE','SPILL','STAFF_MEAL','PREP_WASTE','THEFT_UNKNOWN','OTHER'] as const;
export class Phase7ProfileDto { @IsBoolean() enabled!:boolean; @IsOptional() @IsBoolean() legacyDualMode?:boolean; @IsOptional() @IsIn(NEGATIVE_STOCK_POLICIES) negativeStockPolicy?:string; @IsOptional() @IsBoolean() restockOnRefund?:boolean; @IsOptional() @Type(()=>Number) @IsInt() @Min(0) wasteApprovalThresholdMinor?:number; }
export class Phase7LocationDto { @IsString() name!:string; }
export class Phase7StockItemDto { @IsString() name!:string; @IsOptional() @IsString() sku?:string; @IsOptional() @IsString() categoryId?:string; @IsOptional() @IsString() unit?:string; @IsOptional() @IsString() purchaseUnit?:string; @IsOptional() @Type(()=>Number) @IsInt() @Min(1) purchaseToInventoryFactorMilli?:number; @IsOptional() @IsString() defaultLocationId?:string; @IsOptional() @Type(()=>Number) @IsInt() @Min(0) reorderLevelMilli?:number; @IsOptional() @IsString() preferredSupplierId?:string; @IsOptional() @IsString() purchaseTaxCode?:string; @IsOptional() @Type(()=>Number) @IsInt() @Min(0) purchaseTaxRateBps?:number; @IsOptional() @IsBoolean() negativeStockAllowed?:boolean; }
export class Phase7SupplierDto { @IsString() name!:string; @IsOptional() @IsString() legalName?:string; @IsOptional() @IsString() displayName?:string; @IsOptional() @IsString() taxIdentifier?:string; @IsOptional() @IsString() paymentTerms?:string; @IsOptional() @Type(()=>Number) @IsInt() @Min(0) leadTimeDays?:number; @IsOptional() @IsString() contactName?:string; @IsOptional() @IsString() email?:string; @IsOptional() @IsString() phone?:string; }
export class Phase7RecipeComponentDto { @IsString() stockItemId!:string; @Type(()=>Number) @IsInt() @Min(1) quantityMilli!:number; }
export class Phase7RecipeDto { @IsString() key!:string; @IsString() name!:string; @IsOptional() @IsString() menuItemId?:string; @IsOptional() @Type(()=>Number) @IsInt() @Min(1) yieldMilli?:number; @ValidateNested({each:true}) @Type(()=>Phase7RecipeComponentDto) @IsArray() @ArrayMinSize(1) components!:Phase7RecipeComponentDto[]; }
export class Phase7WasteDto { @IsString() stockItemId!:string; @IsString() locationId!:string; @Type(()=>Number) @IsInt() @Min(1) quantityMilli!:number; @IsIn(WASTE_REASONS) reasonCode!:string; @IsOptional() @IsString() note?:string; @IsOptional() @IsString() attachmentUrl?:string; }
export class Phase7PurchaseOrderLineDto { @IsString() stockItemId!:string; @IsOptional() @Type(()=>Number) @IsInt() @Min(1) orderedMilli?:number; @IsOptional() @Type(()=>Number) @IsInt() @Min(1) orderedPurchaseMilli?:number; @Type(()=>Number) @IsInt() @Min(0) unitCostMinor!:number; }
export class Phase7PurchaseOrderDto { @IsString() supplierId!:string; @IsString() locationId!:string; @IsOptional() @IsString() documentRef?:string; @ValidateNested({each:true}) @Type(()=>Phase7PurchaseOrderLineDto) @IsArray() @ArrayMinSize(1) lines!:Phase7PurchaseOrderLineDto[]; }
export class Phase7ReceiptLineDto { @IsString() stockItemId!:string; @IsOptional() @Type(()=>Number) @IsInt() @Min(1) quantityMilli?:number; @IsOptional() @Type(()=>Number) @IsInt() @Min(1) purchaseQuantityMilli?:number; @IsOptional() @Type(()=>Number) @IsInt() @Min(0) damagedPurchaseMilli?:number; @Type(()=>Number) @IsInt() @Min(0) unitCostMinor!:number; @IsOptional() @IsString() lotBatch?:string; @IsOptional() @IsISO8601() expiresAt?:string; }
export class Phase7ReceiveDto { @IsString() locationId!:string; @IsOptional() @IsString() supplierId?:string; @IsOptional() @IsString() idempotencyKey?:string; @IsOptional() @IsString() invoiceRef?:string; @IsOptional() @IsString() documentRef?:string; @ValidateNested({each:true}) @Type(()=>Phase7ReceiptLineDto) @IsArray() @ArrayMinSize(1) lines!:Phase7ReceiptLineDto[]; }
export class Phase7StocktakeStartDto { @IsString() locationId!:string; @IsOptional() @IsBoolean() blindCount?:boolean; @IsOptional() @IsArray() @IsString({each:true}) stockItemIds?:string[]; }
export class Phase7CountDto { @IsString() stockItemId!:string; @Type(()=>Number) @IsInt() @Min(0) countedMilli!:number; }
export class Phase7StocktakeCountsDto { @ValidateNested({each:true}) @Type(()=>Phase7CountDto) @IsArray() @ArrayMinSize(1) lines!:Phase7CountDto[]; }
export class Phase7QuickStocktakeDto extends Phase7StocktakeCountsDto { @IsString() locationId!:string; @IsOptional() @IsBoolean() blindCount?:boolean; }
export class Phase7TransferDto { @IsString() stockItemId!:string; @IsString() fromLocationId!:string; @IsString() toLocationId!:string; @Type(()=>Number) @IsInt() @Min(1) quantityMilli!:number; @IsOptional() @IsString() note?:string; }
export class Phase7TransferReceiveDto { @Type(()=>Number) @IsInt() @Min(0) receivedMilli!:number; @IsOptional() @Type(()=>Number) @IsInt() @Min(0) damagedMilli?:number; @IsOptional() @IsString() idempotencyKey?:string; @IsOptional() @IsString() note?:string; }
export class Phase7ReverseDto { @IsString() reason!:string; @IsOptional() @IsBoolean() restock?:boolean; }
