export const OFFLINE_POLICY = Object.freeze({
  VIEW_FLOOR: 'ALLOW_LAST_KNOWN',
  SESSION_START: 'EDGE_CERTIFIED',
  SESSION_PAUSE: 'EDGE_CERTIFIED',
  SESSION_RESUME: 'EDGE_CERTIFIED',
  SESSION_END: 'EDGE_CERTIFIED',
  ORDER_CREATE: 'EDGE_CERTIFIED',
  CHECK_CREATE: 'EDGE_CERTIFIED',
  CHECK_UPDATE: 'EDGE_CERTIFIED',
  CASH_PAYMENT: 'EDGE_CERTIFIED_FINANCIAL',
  CARD_PAYMENT: 'PROVIDER_SPECIFIC',
  REFUND: 'ONLINE_ONLY',
  STORED_VALUE: 'ONLINE_ONLY',
  CASH_CLOSE: 'ONLINE_ONLY',
  FISCAL_ISSUE: 'ONLINE_ONLY',
  RATE_CHANGE: 'ONLINE_ONLY',
  PERMISSION_CHANGE: 'ONLINE_ONLY',
  STOCK_RECEIPT: 'ONLINE_ONLY',
  KSEF_SUBMIT: 'COMPLIANCE_DEFERRED',
  PUBLIC_RESERVATION: 'CLOUD_DEPENDENT',
  TICKET_SCAN: 'CACHE_RULE_DEPENDENT',
});

export const CERTIFIED_EDGE_OPERATIONS = new Set([
  'SESSION_START',
  'SESSION_PAUSE',
  'SESSION_RESUME',
  'SESSION_END',
  'ORDER_CREATE',
  'CHECK_CREATE',
  'CHECK_UPDATE',
  'CASH_PAYMENT',
]);

export const NEVER_AUTO_MERGE = new Set([
  'CASH_PAYMENT',
  'CARD_PAYMENT',
  'REFUND',
  'STORED_VALUE',
  'CASH_CLOSE',
  'FISCAL_ISSUE',
]);

export function offlinePolicy(operationType) {
  return OFFLINE_POLICY[operationType] ?? 'ONLINE_ONLY';
}

export function assertCertifiedEdgeOperation(operationType) {
  if (!CERTIFIED_EDGE_OPERATIONS.has(operationType)) {
    throw new Error(`OFFLINE_UNSUPPORTED: ${operationType} is ${offlinePolicy(operationType)}`);
  }
}

export function conflictClass(operationType, code = '') {
  if (NEVER_AUTO_MERGE.has(operationType)) return 'FINANCIAL_MANUAL_REVIEW';
  if (code === 'RESOURCE_CONFLICT') return 'RESOURCE_OPERATOR_RESOLUTION';
  if (code === 'VERSION_CONFLICT') return 'STALE_AGGREGATE_OPERATOR_RESOLUTION';
  if (code === 'RESERVATION_CONFLICT') return 'RESERVATION_OPERATOR_RESOLUTION';
  if (code === 'INVENTORY_CONFLICT') return 'INVENTORY_OPERATOR_RESOLUTION';
  return 'OPERATOR_RESOLUTION';
}
