-- Chunk 15: Workforce
CREATE TABLE "JobRole" ("id" TEXT NOT NULL,"shopId" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "JobRole_pkey" PRIMARY KEY("id"));
CREATE TABLE "EmployeeRate" ("id" TEXT NOT NULL,"shopId" TEXT NOT NULL,"membershipId" TEXT NOT NULL,"jobRoleId" TEXT NOT NULL,"hourlyRateMinor" INTEGER NOT NULL,"currency" TEXT NOT NULL,"effectiveFrom" TIMESTAMP(3) NOT NULL,"effectiveTo" TIMESTAMP(3),"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "EmployeeRate_pkey" PRIMARY KEY("id"));
CREATE TABLE "ScheduleEntry" ("id" TEXT NOT NULL,"shopId" TEXT NOT NULL,"membershipId" TEXT NOT NULL,"jobRoleId" TEXT NOT NULL,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'SCHEDULED',"note" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ScheduleEntry_pkey" PRIMARY KEY("id"));
CREATE TABLE "TimePunch" ("id" TEXT NOT NULL,"shopId" TEXT NOT NULL,"membershipId" TEXT NOT NULL,"scheduleEntryId" TEXT,"jobRoleId" TEXT NOT NULL,"employeeRateId" TEXT NOT NULL,"hourlyRateMinor" INTEGER NOT NULL,"currency" TEXT NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL,"endedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "TimePunch_pkey" PRIMARY KEY("id"));
CREATE TABLE "BreakRecord" ("id" TEXT NOT NULL,"shopId" TEXT NOT NULL,"timePunchId" TEXT NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL,"endedAt" TIMESTAMP(3),"paid" BOOLEAN NOT NULL DEFAULT false,"note" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BreakRecord_pkey" PRIMARY KEY("id"));
CREATE TABLE "TimeAdjustment" ("id" TEXT NOT NULL,"shopId" TEXT NOT NULL,"timePunchId" TEXT NOT NULL,"proposedStartedAt" TIMESTAMP(3),"proposedEndedAt" TIMESTAMP(3),"proposedUnpaidBreakSeconds" INTEGER,"reason" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"requestedById" TEXT NOT NULL,"decidedById" TEXT,"decisionNote" TEXT,"decidedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TimeAdjustment_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "JobRole_shopId_name_key" ON "JobRole"("shopId","name"); CREATE UNIQUE INDEX "JobRole_shopId_code_key" ON "JobRole"("shopId","code"); CREATE INDEX "JobRole_shopId_active_sortOrder_idx" ON "JobRole"("shopId","active","sortOrder");
CREATE INDEX "EmployeeRate_shopId_membershipId_jobRoleId_effectiveFrom_idx" ON "EmployeeRate"("shopId","membershipId","jobRoleId","effectiveFrom"); CREATE INDEX "EmployeeRate_shopId_effectiveFrom_effectiveTo_idx" ON "EmployeeRate"("shopId","effectiveFrom","effectiveTo");
CREATE INDEX "ScheduleEntry_shopId_membershipId_startsAt_idx" ON "ScheduleEntry"("shopId","membershipId","startsAt"); CREATE INDEX "ScheduleEntry_shopId_startsAt_endsAt_idx" ON "ScheduleEntry"("shopId","startsAt","endsAt");
CREATE INDEX "TimePunch_shopId_membershipId_startedAt_idx" ON "TimePunch"("shopId","membershipId","startedAt"); CREATE INDEX "TimePunch_shopId_startedAt_endedAt_idx" ON "TimePunch"("shopId","startedAt","endedAt");
CREATE INDEX "BreakRecord_shopId_timePunchId_startedAt_idx" ON "BreakRecord"("shopId","timePunchId","startedAt");
CREATE INDEX "TimeAdjustment_shopId_timePunchId_status_createdAt_idx" ON "TimeAdjustment"("shopId","timePunchId","status","createdAt"); CREATE INDEX "TimeAdjustment_shopId_status_createdAt_idx" ON "TimeAdjustment"("shopId","status","createdAt");
